### ISSUE TITLE
Nccl version not compatible with cuda 9.1, please tell me if to upgrade cuda version or downgrade nccl version, pytorch version is 1.10.0

### ISSUE THREAD

**Issue by KAKAROT12419** [NVIDIA/nccl#1068]
```
Start with 'tensorboard --logdir Akash/yolov5/yolov5/runs/train', view at http://localhost:6006/
nvidia2020:27646:27646 [0] NCCL INFO Bootstrap : Using enp1s0f0:10.100.12.111<0>
nvidia2020:27646:27646 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
nvidia2020:27646:27646 [0] NCCL INFO NET/IB : No device found.
nvidia2020:27646:27646 [0] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.100.12.111<0>
nvidia2020:27646:27646 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.1
nvidia2020:27649:27649 [3] NCCL INFO Bootstrap : Using enp1s0f0:10.100.12.111<0>
nvidia2020:27649:27649 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
nvidia2020:27648:27648 [2] NCCL INFO Bootstrap : Using enp1s0f0:10.100.12.111<0>
nvidia2020:27647:27647 [1] NCCL INFO Bootstrap : Using enp1s0f0:10.100.12.111<0>
nvidia2020:27648:27648 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
nvidia2020:27647:27647 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
nvidia2020:27649:27649 [3] NCCL INFO NET/IB : No device found.
nvidia2020:27649:27649 [3] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.100.12.111<0>
nvidia2020:27649:27649 [3] NCCL INFO Using network Socket
nvidia2020:27648:27648 [2] NCCL INFO NET/IB : No device found.
nvidia2020:27647:27647 [1] NCCL INFO NET/IB : No device found.
nvidia2020:27648:27648 [2] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.100.12.111<0>
nvidia2020:27648:27648 [2] NCCL INFO Using network Socket
nvidia2020:27647:27647 [1] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.100.12.111<0>
nvidia2020:27647:27647 [1] NCCL INFO Using network Socket
nvidia2020:27647:27928 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
nvidia2020:27647:27928 [1] NCCL INFO Setting affinity for GPU 4 to ff,fff00000
nvidia2020:27648:27927 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
nvidia2020:27648:27927 [2] NCCL INFO Setting affinity for GPU 5 to ff,fff00000
nvidia2020:27649:27929 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
nvidia2020:27649:27929 [3] NCCL INFO Setting affinity for GPU 6 to ff,fff00000
nvidia2020:27646:27925 [0] NCCL INFO Channel 00/02 :    0   1   2   3
nvidia2020:27646:27925 [0] NCCL INFO Channel 01/02 :    0   1   2   3
nvidia2020:27646:27925 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
nvidia2020:27646:27925 [0] NCCL INFO Setting affinity for GPU 3 to 0fffff
nvidia2020:27648:27927 [2] NCCL INFO Channel 00 : 2[86000] -> 3[89000] via P2P/IPC
nvidia2020:27649:27929 [3] NCCL INFO Channel 00 : 3[89000] -> 0[b000] via direct shared memory
nvidia2020:27648:27927 [2] NCCL INFO Channel 01 : 2[86000] -> 3[89000] via P2P/IPC
nvidia2020:27649:27929 [3] NCCL INFO Channel 01 : 3[89000] -> 0[b000] via direct shared memory
nvidia2020:27647:27928 [1] NCCL INFO Channel 00 : 1[85000] -> 2[86000] via P2P/IPC
nvidia2020:27646:27925 [0] NCCL INFO Channel 00 : 0[b000] -> 1[85000] via direct shared memory
nvidia2020:27647:27928 [1] NCCL INFO Channel 01 : 1[85000] -> 2[86000] via P2P/IPC

nvidia2020:27648:27927 [2] transport/p2p.cc:136 NCCL WARN Cuda failure 'API call is not supported in the installed CUDA driver'
nvidia2020:27648:27927 [2] NCCL INFO transport/p2p.cc:238 -> 1
nvidia2020:27648:27927 [2] NCCL INFO transport.cc:111 -> 1
nvidia2020:27648:27927 [2] NCCL INFO init.cc:778 -> 1
nvidia2020:27648:27927 [2] NCCL INFO init.cc:904 -> 1
nvidia2020:27648:27927 [2] NCCL INFO group.cc:72 -> 1 [Async thread]
nvidia2020:27646:27925 [0] NCCL INFO Channel 01 : 0[b000] -> 1[85000] via direct shared memory

nvidia2020:27647:27928 [1] transport/p2p.cc:136 NCCL WARN Cuda failure 'API call is not supported in the installed CUDA driver'
nvidia2020:27647:27928 [1] NCCL INFO transport/p2p.cc:238 -> 1
nvidia2020:27647:27928 [1] NCCL INFO transport.cc:111 -> 1
nvidia2020:27647:27928 [1] NCCL INFO init.cc:778 -> 1
nvidia2020:27647:27928 [1] NCCL INFO init.cc:904 -> 1
nvidia2020:27647:27928 [1] NCCL INFO group.cc:72 -> 1 [Async thread]

nvidia2020:27649:27929 [3] transport/p2p.cc:136 NCCL WARN Cuda failure 'API call is not supported in the installed CUDA driver'
nvidia2020:27649:27929 [3] NCCL INFO transport/p2p.cc:262 -> 1
nvidia2020:27649:27929 [3] NCCL INFO transport.cc:119 -> 1
nvidia2020:27649:27929 [3] NCCL INFO init.cc:778 -> 1
nvidia2020:27649:27929 [3] NCCL INFO init.cc:904 -> 1
nvidia2020:27649:27929 [3] NCCL INFO group.cc:72 -> 1 [Async thread]
Traceback (most recent call last):
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 651, in <module>
    main(opt)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 540, in main
nvidia2020:27646:27925 [0] NCCL INFO Connected all rings
    train(opt.hyp, opt, device, callbacks)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 120, in train
Traceback (most recent call last):
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 651, in <module>
    with torch_distributed_zero_first(LOCAL_RANK):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/akshatt/Akash/yolov5/yolov5/utils/torch_utils.py", line 92, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
    main(opt)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 540, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 120, in train
    with torch_distributed_zero_first(LOCAL_RANK):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/akshatt/Akash/yolov5/yolov5/utils/torch_utils.py", line 92, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
Traceback (most recent call last):
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 651, in <module>
    main(opt)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 540, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/akshatt/Akash/yolov5/yolov5/train.py", line 120, in train
    with torch_distributed_zero_first(LOCAL_RANK):
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/akshatt/Akash/yolov5/yolov5/utils/torch_utils.py", line 92, in torch_distributed_zero_first
    dist.barrier(device_ids=[local_rank])
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27646 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27647 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 27648) of binary: /home/akshatt/anaconda3/envs/yolov5update/bin/python
Traceback (most recent call last):
  File "/home/akshatt/anaconda3/envs/yolov5update/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/akshatt/anaconda3/envs/yolov5update/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/akshatt/Akash/yolov5/yolov5/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-14_06:55:57
  host      : NVIDIA2020
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 27649)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-14_06:55:57
  host      : NVIDIA2020
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 27648)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by KAKAROT12419** [comment]
how can upgrade my cuda toolkit to 10.2 or 11 . Can you please tellthe command or procedure because i am getting confused after  seeing lots of stuff online
