### ISSUE TITLE
nvlink error   : Undefined reference to 'ncclDevFuncTable' in '/home/hhhyzzz/nccl/build/obj/device/common.cu.o' 

### ISSUE THREAD

**Issue by MLS2021** [NVIDIA/nccl#1106]
After I cloned the nccl code, I followed the instructions in Build .  When I finish this step:
`$ make -j src.build NVCC_GENCODE="-gencode=arch=compute_89,code=sm_89"`
I got this :
`nvlink error   : Undefined reference to 'ncclDevFuncTable' in '/home/hhhyzzz/nccl/build/obj/device/common.cu.o' `

Then, I tried to run a sample code about nccl. I got this :

/home/hhhyzzz/miniconda3/bin/python /home/hhhyzzz/Code/test/test.py 
Running DDP example on rank 1.
Running DDP example on rank 0.
initial finished
Rank 0/2 initialized
initial finished
Rank 1/2 initialized
[E ProcessGroupNCCL.cpp:475] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800575 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800661 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800661 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800575 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/hhhyzzz/Code/test/test.py", line 66, in <module>
    main()
  File "/home/hhhyzzz/Code/test/test.py", line 63, in main
    mp.spawn(demo_ddp, args=(world_size,), nprocs=world_size, join=True)
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/hhhyzzz/Code/test/test.py", line 43, in demo_ddp
    ddp_model = DDP(model, device_ids=[rank])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: DDP expects same model across all ranks, but Rank 1 has 4 params, while rank 0 has inconsistent 0 params.

进程已结束，退出代码为 1

My env is python=3.9.8 + cuda12.1 + cudnn8.9 

Here's the program stuck:
def demo_ddp(rank, world_size):
    print(f"Running DDP example on rank {rank}.")

    # Initialize distributed environment for each process
    setup(rank, world_size)

    # Print the rank and world size to see the progress
    print(f"Rank {rank}/{world_size} initialized")

    # Create model and move it to GPU with id rank
    model = ToyModel().to(rank)

    ddp_model = DDP(model, device_ids=[rank])
    
hopely got help

**Comment by srishtih** [comment]
Did you manage to resolve this issue?

**Comment by AspartameJ** [comment]
> After I cloned the nccl code, I followed the instructions in Build . When I finish this step: `$ make -j src.build NVCC_GENCODE="-gencode=arch=compute_89,code=sm_89"` I got this : `nvlink error : Undefined reference to 'ncclDevFuncTable' in '/home/hhhyzzz/nccl/build/obj/device/common.cu.o' `
> 
> Then, I tried to run a sample code about nccl. I got this :
> 
> /home/hhhyzzz/miniconda3/bin/python /home/hhhyzzz/Code/test/test.py Running DDP example on rank 1. Running DDP example on rank 0. initial finished Rank 0/2 initialized initial finished Rank 1/2 initialized [E ProcessGroupNCCL.cpp:475] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800575 milliseconds before timing out. [E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800661 milliseconds before timing out. [E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. [E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down. [E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800661 milliseconds before timing out. [E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. [E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down. [E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800575 milliseconds before timing out. Traceback (most recent call last): File "/home/hhhyzzz/Code/test/test.py", line 66, in main() File "/home/hhhyzzz/Code/test/test.py", line 63, in main mp.spawn(demo_ddp, args=(world_size,), nprocs=world_size, join=True) File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method="spawn") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes while not context.join(): ^^^^^^^^^^^^^^ File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 163, in join raise ProcessRaisedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 1 terminated with the following error: Traceback (most recent call last): File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap fn(i, *args) File "/home/hhhyzzz/Code/test/test.py", line 43, in demo_ddp ddp_model = DDP(model, device_ids=[rank]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 795, in **init** _verify_param_shape_across_processes(self.process_group, parameters) File "/home/hhhyzzz/miniconda3/lib/python3.11/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes return dist._verify_params_across_processes(process_group, tensors, logger) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: DDP expects same model across all ranks, but Rank 1 has 4 params, while rank 0 has inconsistent 0 params.
> 
> 进程已结束，退出代码为 1
> 
> My env is python=3.9.8 + cuda12.1 + cudnn8.9
> 
> Here's the program stuck: def demo_ddp(rank, world_size): print(f"Running DDP example on rank {rank}.")
> 
> ```
> # Initialize distributed environment for each process
> setup(rank, world_size)
> 
> # Print the rank and world size to see the progress
> print(f"Rank {rank}/{world_size} initialized")
> 
> # Create model and move it to GPU with id rank
> model = ToyModel().to(rank)
> 
> ddp_model = DDP(model, device_ids=[rank])
> ```
> 
> hopely got help

$ find . -type f -exec dos2unix {} \;

**Comment by MouseSun846** [comment]
I have also encountered the same problem. Have you solved it?
```
(base) root@DESKTOP-P54EAF3:/mnt/d/Code/nccl# make -j src.build NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70"
make -C src build BUILDDIR=/mnt/d/Code/nccl/build
make[1]: Entering directory '/mnt/d/Code/nccl/src'
NVCC_GENCODE is -gencode=arch=compute_70,code=sm_70
make[2]: Entering directory '/mnt/d/Code/nccl/src/device'
NVCC_GENCODE is -gencode=arch=compute_70,code=sm_70
nvlink error   : Undefined reference to 'ncclDevFuncTable' in '/mnt/d/Code/nccl/build/obj/device/common.cu.o'
Makefile:90: recipe for target '/mnt/d/Code/nccl/build/obj/device/device_glue.o' failed
make[2]: *** [/mnt/d/Code/nccl/build/obj/device/device_glue.o] Error 255
make[2]: Leaving directory '/mnt/d/Code/nccl/src/device'
Makefile:56: recipe for target '/mnt/d/Code/nccl/build/obj/device/manifest' failed
make[1]: *** [/mnt/d/Code/nccl/build/obj/device/manifest] Error 2
make[1]: Leaving directory '/mnt/d/Code/nccl/src'
Makefile:25: recipe for target 'src.build' failed
make: *** [src.build] Error 2
```

**Comment by MLS2021** [comment]
> Did you manage to resolve this issue?
I'm very sorry for not noticing your question. If it hasn't been resolved, please check my reply below.

**Comment by MouseSun846** [comment]
> > Did you manage to resolve this issue?
> > I'm very sorry for not noticing your question. If it hasn't been resolved, please check my reply above.

Thank you for your suggestion. I will try to solve it

**Comment by Superkeyv** [comment]
I noticed you probably used wsl to compile nccl.
The default EOL is CRLF in windows rather LF，you should change EOL of src/device/generate.py to LF， and try again

Hope this helps.

**Comment by MouseSun846** [comment]
Thank you for your suggestion. I haved already to solve it.

**Comment by risqaliyevds** [comment]
How did you solve it @MouseSun846 ?

**Comment by MouseSun846** [comment]
> How did you solve it [@MouseSun846](https://github.com/MouseSun846) ?
It seems to be a line break issue. Win is different from Linux.
