### ISSUE TITLE
ncclSystemError: System call (socket, malloc, munmap, etc) failed

### ISSUE THREAD

**Issue by marcelchee** [NVIDIA/nccl#1113]
I am encountering an issue when attempting to run my script using PyTorch distributed training with NCCL on WSL 2. The error seems to be related to a failure in a system call, leading to an NCCL version 2.7.8 error. Running step 3 of [this repo](https://github.com/rmaphoh/RETFound_MAE/tree/main).

Environment:
GPU: NVIDIA 2080Ti
OS: Linux on Ubuntu through WSL 2
nvcc: NVIDIA (R) Cuda compilation tools, release 11.5, V11.5.119
NVIDIA-SMI 535.129.03             Driver Version: 546.29       CUDA Version: 12.3
Python 3.7.5
torch version: 1.8.1+cu111

Error trace:
python -m torch.distributed.launch --nproc_per_node=1 --master_port=48798 main_finetune.py     --batch_size 16     --world_size 1     --model vit_large_patch16     --epochs 50     --blr 5e-3 --layer_decay 0.65     --weight_decay 0.05 --drop_path 0.2     --nb_classes 5     --data_path ./IDRiD_data/     --task ./finetune_IDRiD/     --finetune ./RETFound_cfp_weights.pth     --input_size 224
| distributed init (rank 0): env://, gpu 0
Traceback (most recent call last):
  File "main_finetune.py", line 377, in <module>
    main(args)
  File "main_finetune.py", line 155, in main
    misc.init_distributed_mode(args)
  File "/home/marcel/foundationmd/retfound_cph/RETFound_MAE/util/misc.py", line 241, in init_distributed_mode
    torch.distributed.barrier()
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Killing subprocess 18942
Traceback (most recent call last):
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/marcel/miniconda3/envs/retfound/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marcel/miniconda3/envs/retfound/bin/python', '-u', 'main_finetune.py', '--local_rank=0', '--batch_size', '16', '--world_size', '1', '--model', 'vit_large_patch16', '--epochs', '50', '--blr', '5e-3', '--layer_decay', '0.65', '--weight_decay', '0.05', '--drop_path', '0.2', '--nb_classes', '5', '--data_path', './IDRiD_data/', '--task', './finetune_IDRiD/', '--finetune', './RETFound_cfp_weights.pth', '--input_size', '224']' returned non-zero exit status 1.

Attempted fixes:
I have tried NCCL_DEBUG=WARN, NCCL_SOCKET_IFNAME==ens1f0, and NCCL_DEBUG=INFO but the error output remained the same.
I also tried a reinstall of nccl with no success.

**Comment by AddyLaddy** [comment]
NCCL 2.7.8 is very old (7/24/2020) and we didn't add any WSL2 support until NCCL 2.10.x
Can you try with a more recent NCCL version such as 2.18.5 or 2.19.4 from github?
