### ISSUE TITLE
Internal error during recv

### ISSUE THREAD

**Issue by jnordberg** [NVIDIA/nccl#1140]
[error.log](https://github.com/NVIDIA/nccl/files/13853819/error.log)
```
... (truncated due to github size limits, see error.log) ..
Root Cause (first observed failure):
[0]:
  time      : 2024-01-07_14:16:40
  host      : mockingbird-3-8xA100
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 243424)
  error_file: /tmp/torchelastic_4ot7pll6/none_2e1tb1p8/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/home/ubuntu/micromamba/envs/aviary/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
    File "/home/ubuntu/code/aviary/src/cyberfowl/data_baker.py", line 178, in run
      results = gather_data(batch, rank, world_size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/ubuntu/code/aviary/src/cyberfowl/data_baker.py", line 204, in gather_data
      waiting.append(dist.irecv(tensor=recv_tensor[i], src=i))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/ubuntu/micromamba/envs/aviary/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1565, in irecv
      return pg.recv([tensor], src, tag)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  RuntimeError: NCCL Error 3: internal error - please report this issue to the NCCL developers

============================================================
```

```
$ nvidia-smi
Sun Jan  7 14:24:18 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          On  | 00000000:06:00.0 Off |                    0 |
| N/A   28C    P0              55W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          On  | 00000000:07:00.0 Off |                    0 |
| N/A   27C    P0              53W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-40GB          On  | 00000000:08:00.0 Off |                    0 |
| N/A   27C    P0              52W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-40GB          On  | 00000000:09:00.0 Off |                    0 |
| N/A   27C    P0              53W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM4-40GB          On  | 00000000:0A:00.0 Off |                    0 |
| N/A   27C    P0              53W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM4-40GB          On  | 00000000:0B:00.0 Off |                    0 |
| N/A   27C    P0              50W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM4-40GB          On  | 00000000:0C:00.0 Off |                    0 |
| N/A   27C    P0              50W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM4-40GB          On  | 00000000:0D:00.0 Off |                    0 |
| N/A   27C    P0              52W / 400W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by jnordberg** [comment]
Looks like the underlying cause is a simple OOM
