### ISSUE TITLE
ValueError: bytes must be in range(0, 256)

### ISSUE THREAD

**Issue by NavinKumarMNK** [NVIDIA/nccl#1237]
When i started my `vllm` engine i am getting an error message `bytes must be in the range (0, 256)` it seems the error is coming from `NCCLBackendWithBFloat16()` . When i set `enforce_eager=True` then the error is not occuring.

> os: ubuntu 22.04 ppc64le, 4 V100 gpu.
> cuda: 12.2 
> vllm version: 0.33.0

### Code
```python
from vllm import LLM, SamplingParams
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(
    model="./models", 
    dtype="float16", 
    tensor_parallel_size=4, 
    #enforce_eager=True, 
    trust_remote_code=True, 
    load_format='safetensors'
)
outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

### Error
```bash
root@3b4826375ab0:/workspace# NCCL_DEBUG=INFO python3 example.py 
WARNING 03-25 15:47:22 config.py:686] Casting torch.bfloat16 to torch.float16.
2024-03-25 15:47:27,911 INFO worker.py:1612 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
INFO 03-25 15:47:34 llm_engine.py:68] Initializing an LLM engine (v0.3.3) with config: model='./models', tokenizer='./models', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=safetensors, tensor_parallel_size=4, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
3b4826375ab0:14697:14697 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
3b4826375ab0:14697:14697 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
Traceback (most recent call last):
  File "/workspace/example.py", line 10, in <module>
    llm = LLM(
  File "/root/vllm/vllm/entrypoints/llm.py", line 109, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/root/vllm/vllm/engine/llm_engine.py", line 146, in from_engine_args
    engine = cls(*engine_configs,
  File "/root/vllm/vllm/engine/llm_engine.py", line 103, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/root/vllm/vllm/executor/ray_gpu_executor.py", line 60, in __init__
    self._init_workers_ray(placement_group)
  File "/root/vllm/vllm/executor/ray_gpu_executor.py", line 190, in _init_workers_ray
    self._run_workers("init_device",
  File "/root/vllm/vllm/executor/ray_gpu_executor.py", line 318, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/root/vllm/vllm/worker/worker.py", line 92, in init_device
    init_distributed_environment(self.parallel_config, self.rank,
  File "/root/vllm/vllm/worker/worker.py", line 276, in init_distributed_environment
    cupy_utils.init_process_group(
  File "/root/vllm/vllm/model_executor/parallel_utils/cupy_utils.py", line 90, in init_process_group
    _NCCL_BACKEND = NCCLBackendWithBFloat16(world_size, rank, host, port)
  File "/root/miniconda3/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 70, in __init__
    self._init_with_tcp_store(n_devices, rank, host, port)
  File "/root/miniconda3/lib/python3.10/site-packages/cupyx/distributed/_nccl_comm.py", line 93, in _init_with_tcp_store
    shifted_nccl_id = bytes([b + 128 for b in nccl_id])
ValueError: bytes must be in range(0, 256)
```

Thanks. Let me know if any more information is required

**Comment by sjeaugey** [comment]
I don't see any NCCL error. This seems to be coming from PyTorch.

**Comment by NavinKumarMNK** [comment]
alright! can you provider any supporting statements . or logic to debug ?
and how it seems to be coming from pytorch ?

**Comment by sjeaugey** [comment]
The `ValueError: bytes must be in range(0, 256)` is not coming from NCCL.
Also I don't see any `NCCL WARN` in the log.

**Comment by NavinKumarMNK** [comment]
ok fine. do you have any idea to debug ? solve the problem. or let me close the issue

**Comment by sjeaugey** [comment]
I have never seen that in the past, so no, I have no clue unfortunately.

**Comment by NavinKumarMNK** [comment]
any debug methods that will help to find the reason ?

**Comment by sjeaugey** [comment]
Again, I don't know how to debug this given the error is not in NCCL. I know plenty of strategies to debug NCCL issues, but none to debug a component I'm not familiar with.

**Comment by NavinKumarMNK** [comment]
alright thanks!
