### ISSUE TITLE
'NCCLCommunicator' object has no attribute 'comm'

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/nccl#1257]
I'm running vllm on 2 machines each with 4 V100 GPUs.

Their driver versions are not the same, they are `Driver Version: 535.161.08`  and `Driver Version: 535.161.07`.

I try to run vllm using 8 GPUs across machines, but it reports error:

```
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 100, in init_device
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     init_distributed_environment(self.parallel_config, self.rank,
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 287, in init_distributed_environment
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     pynccl_utils.init_process_group(
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl_utils.py", line 46, in init_process_group
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     comm = NCCLCommunicator(init_method=init_method,
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 236, in __init__
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     dist.broadcast(tensor, src=0)
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44]     work = default_pg.broadcast([tensor], opts)
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, internal error - please report this is
sue to the NCCL developers, NCCL version 2.18.1
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] ncclInternalError: Internal check failed.
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] Last error:
(RayWorkerVllm pid=454418) ERROR 04-18 01:56:15 ray_utils.py:44] Socket recv failed while polling for opId=0x7f3a59f329b0
(RayWorkerVllm pid=454418) Exception ignored in: <function NCCLCommunicator.__del__ at 0x7f435029d2d0>
(RayWorkerVllm pid=454418) Traceback (most recent call last):
(RayWorkerVllm pid=454418)   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
(RayWorkerVllm pid=454418)     _c_ncclCommDestroy(self.comm)
(RayWorkerVllm pid=454418) AttributeError: 'NCCLCommunicator' object has no attribute 'comm'
(RayWorkerVllm pid=454499) ERROR 04-18 01:56:15 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DE
BUG=INFO for details), NCCL version 2.18.1
(RayWorkerVllm pid=454499) ERROR 04-18 01:56:15 ray_utils.py:44] ncclUnhandledCudaError: Call to CUDA function failed.
(RayWorkerVllm pid=454499) ERROR 04-18 01:56:15 ray_utils.py:44] Cuda failure 'invalid argument'
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, remote process exited or there was a n
etwork error, NCCL version 2.18.1
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] ncclRemoteError: A call failed possibly due to a network error or a remote process exiting prematurely.
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] socketStartConnect: exceeded retries (20000)
(RayWorkerVllm pid=454581) INFO 04-18 01:56:13 selector.py:40] Cannot use FlashAttention backend for Volta and Turing GPUs. [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to
disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=454581) INFO 04-18 01:56:13 selector.py:25] Using XFormers backend. [repeated 7x across cluster]
(RayWorkerVllm pid=454581) INFO 04-18 01:56:13 pynccl_utils.py:45] vLLM is using nccl==2.18.1 [repeated 7x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution. [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] Traceback (most recent call last): [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 37, in execute_method [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     return executor(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 100, in init_device [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     init_distributed_environment(self.parallel_config, self.rank, [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 287, in init_distributed_environment [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     pynccl_utils.init_process_group( [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl_utils.py", line 46, in init_process_group [repeated 2x ac
ross cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     comm = NCCLCommunicator(init_method=init_method, [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 236, in __init__ [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     dist.broadcast(tensor, src=0) [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     return func(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44]     work = default_pg.broadcast([tensor], opts) [repeated 2x across cluster]
(RayWorkerVllm pid=454337) ERROR 04-18 01:56:38 ray_utils.py:44] Last error: [repeated 2x across cluster]
(RayWorkerVllm pid=454337) Exception ignored in: <function NCCLCommunicator.__del__ at 0x7f17c83392d0> [repeated 2x across cluster]
(RayWorkerVllm pid=454337) Traceback (most recent call last): [repeated 2x across cluster]
(RayWorkerVllm pid=454337)   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__ [repeated 2x across cluster]
(RayWorkerVllm pid=454337)     _c_ncclCommDestroy(self.comm) [repeated 2x across cluster]
(RayWorkerVllm pid=454337) AttributeError: 'NCCLCommunicator' object has no attribute 'comm' [repeated 2x across cluster]
```

Here is my script:
```shell
# on the head node: 
ray start --head 

# on the worker node
ray start --address="xxx.xx:xxxx"

# on the head node: 
python -m vllm.entrypoints.openai.api_server     --model /data/models/vicuna-13b-v1.5/ --disable-log-requests     -tp 8 --gpu-memory-utilization 0.84 --engine-use-ray --worker-use-ray
```

my script to start container on both machines:
```
sudo docker run -it --privileged --gpus all --network host --shm-size=32g --name $1  \
        -v /data/:/data/       -v /data/docker_home:/root/ \
        $2 /bin/bash
```

**Comment by sleepwalker2017** [comment]
using ray status, I can see there are 8 GPUs in the cluster

```shell
# ray status
======== Autoscaler status: 2024-04-18 02:01:24.864823 ========
Node status
---------------------------------------------------------------
Active:
 1 node_87b7b5cbadc618c0e446c5c5029e87a920c43390cd5ebef78881842e
 1 node_ec64d7047e4efb5078727c4ec8e26da1c630f9b60d25198268d5c8b0
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/96.0 CPU
 8.0/8.0 GPU (8.0 used of 8.0 reserved in placement groups)
 0B/431.43GiB memory
 0B/60.69GiB object_store_memory
```

**Comment by sleepwalker2017** [comment]
The latest error:

```
(_AsyncLLMEngine pid=26491, ip=10.12.3.163) INFO 04-18 03:05:02 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/data/models/vicuna-13b-v1.5/', tokenizer='/data/models/vicuna-13b-v1.5/', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=8, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
(_AsyncLLMEngine pid=26491, ip=10.12.3.163) Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(_AsyncLLMEngine pid=26491, ip=10.12.3.163) INFO 04-18 03:05:23 selector.py:40] Cannot use FlashAttention backend for Volta and Turing GPUs.
(_AsyncLLMEngine pid=26491, ip=10.12.3.163) INFO 04-18 03:05:23 selector.py:25] Using XFormers backend.
(RayWorkerVllm pid=26676, ip=10.12.3.163) INFO 04-18 03:05:24 pynccl_utils.py:45] vLLM is using nccl==2.18.1
(RayWorkerVllm pid=484292) Exception ignored in: <function NCCLCommunicator.__del__ at 0x7fa4882212d0>
(RayWorkerVllm pid=484292) Traceback (most recent call last):
(RayWorkerVllm pid=484292)   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
(RayWorkerVllm pid=484292)     _c_ncclCommDestroy(self.comm)
(RayWorkerVllm pid=484292) AttributeError: 'NCCLCommunicator' object has no attribute 'comm'
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 100, in init_device
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     init_distributed_environment(self.parallel_config, self.rank,
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 287, in init_distributed_environment
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     pynccl_utils.init_process_group(
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl_utils.py", line 46, in init_process_group
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     comm = NCCLCommunicator(init_method=init_method,
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/parallel_utils/pynccl.py", line 236, in __init__
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     dist.broadcast(tensor, src=0)
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44]     work = default_pg.broadcast([tensor], opts)
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] ncclInternalError: Internal check failed.
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] Last error:
(RayWorkerVllm pid=484292) ERROR 04-18 03:05:26 ray_utils.py:44] Socket recv failed while polling for opId=0x7f9b65f329b0
(RayWorkerVllm pid=484357) ERROR 04-18 03:05:26 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
(RayWorkerVllm pid=484357) ERROR 04-18 03:05:26 ray_utils.py:44] ncclUnhandledCudaError: Call to CUDA function failed.
(RayWorkerVllm pid=484357) ERROR 04-18 03:05:26 ray_utils.py:44] Cuda failure 'invalid argument'
```

**Comment by Lzhang-hub** [comment]
I have same error, had you resolve it?

**Comment by sleepwalker2017** [comment]
> I have same error, had you resolve it?

No I didn't find why. That's strange.

**Comment by JasonCZH4** [comment]
Any progress?

**Comment by sjeaugey** [comment]
You should set `NCCL_DEBUG=INFO` (or `WARN` at least) to see which CUDA call failed and why.
