### ISSUE TITLE
panic when compute the paths in exsi

### ISSUE THREAD

**Issue by gangxie112** [NVIDIA/nccl#1547]
Hi,

I setup a test bed with exsi with p40. p40 is passed through to the linux host. When I run nccl-tests and it panic when compute the path. After some debug, I find that it doesn't set the path correctly:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ncclTopoComputePaths (system=0x7f6941a39010, comm=0x5611476b1a00) at graph/paths.cc:618
618           if (gpu->paths[NET][n].type < PATH_PHB) {
[Current thread is 1 (Thread 0x7f694a3ba000 (LWP 4141))]
(gdb) bt
#0  ncclTopoComputePaths (system=0x7f6941a39010, comm=0x5611476b1a00) at graph/paths.cc:618
#1  0x00007f6973cd3a38 in initTransportsRank (comm=0x5611476b1a00, parent=0x0, timers=0x7f694a3b3810) at init.cc:856
#2  0x00007f6973cd90c2 in ncclCommInitRankFunc (job_=0x5611476f0680) at init.cc:1462
#3  0x00007f6973cc1137 in ncclAsyncJobMain (arg=0x5611476f0680) at group.cc:73
#4  0x00007f6973790ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007f6973822850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) p gpu.paths
$1 = {0x7f636ee55380, 0x0, 0x0, 0x0, 0x0, 0x0}
```

The nccl version is v2.23.4-1, and I checked older version , the same panic could be seen. 

I  spend some time to dig more , and found the virtual host has the following graph, both nic and gpu are in the same pci bus. 

```
<system version="1">
  <cpu host_hash="0x3644ad02af4b0580" numaid="0" affinity="ffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="79">
    <pci busid="0000:03:00.0" class="0x030200" vendor="0x10de" device="0x1b38" subsystem_vendor="0x10de" subsystem_device="0x11d9" link_speed="5.0 GT/s PCIe" link_width="0">
      <gpu dev="0" sm="61" rank="0" gdr="1"/>
      <nic>
        <net name="mlx5_0" dev="0" speed="100000" port="1" latency="0.000000" guid="0x709ff200032d1de4" maxconn="262144" gdr="0"/>
      </nic>
    </pci>
  </cpu>
</system>
```

**Comment by gangxie112** [comment]
After some investigation, I found  that exsi 8x always map all the path-through pci to one pci node. Not sure how to modify the rule. After I dowgrade the exsi to 6.x, it works fine.
