### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:264, unhandled system error

### ISSUE THREAD

**Issue by SnailTyan** [NVIDIA/nccl#293]
Hi NCCL team,

I'm using pytorch distributed training with 8 Tesla V100 GPU in single machine. I met  some NCCL errors after training for a while. The training env is:

```
Docker: nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04
Pytorch: 1.2.0
CUDA: 10.1
NCCL: 2.4.8
```

The error log is as follows:

```
[2/20][4083/7614] Loss: 8.699026
42692884fcba:140:39062 [0] NCCL INFO Setting affinity for GPU 0 to 3ff003ff
42692884fcba:140:39062 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees enabled up to size -2
42692884fcba:140:39062 [0] NCCL INFO comm 0x7f558bec9670 rank 0 nranks 1 cudaDev 0 nvmlDev 0 - Init COMPLETE
2020-02-17 19:30:48
[2/20][4084/7614] Loss: 9.590029

42692884fcba:140:140 [0] include/socket.h:333 NCCL WARN Call to bind failed : Address already in use
42692884fcba:140:140 [0] NCCL INFO bootstrap.cc:91 -> 2
42692884fcba:140:140 [0] NCCL INFO bootstrap.cc:245 -> 2
42692884fcba:140:140 [0] NCCL INFO bootstrap.cc:266 -> 2
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main()
  File "train.py", line 182, in main
    train(opt)
  File "train.py", line 135, in train
    average_gradients(model)
  File "train.py", line 49, in average_gradients
    dist.all_reduce(param.grad.data, op=dist.reduce_op.SUM, group=dist_group)
  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:264, unhandled system error
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', u'-u', 'train.py', u'--local_rank=7', '--adadelta', '--train_root', 'train_lmdb', '--epochs', '20', '--batch_size', '256', '--pretrained_model', 'pretrained_model.pth']' returned non-zero exit status 1
```

After training for a while, this error will appear. 

How could I solve it? Any help or suggestion is appreciable.

Thanks.

**Comment by SnailTyan** [comment]
I have run nccl-test using this command it run perfectly.
```
./build/all_reduce_perf -b 8 -e 256M -f 2 -g 8
```
