### ISSUE TITLE
pytorch Multi-GPU program hangs with unblance threads?

### ISSUE THREAD

**Issue by Approximetal** [NVIDIA/nccl#383]
Hi, I was trying to use DistributeDataParallel for training. It all works well on single GPU, but when I try to use 2 GPUs, it hangs, and the Debug Info is as follow:
Any Thing I can do to deal with it?
```
(py36) [zhiyuan.zhao@cloud-tts parrotron]$ CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 train_vc2_wavernn.py --gpu_name=1,2
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

GPU Memory Track | 03-Sep-20-14:21:41 | Total Used Memory:1470.7 Mb

FP16 Run: True
Dynamic Loss Scaling: True
cuDNN Enabled: True
cuDNN Benchmark: False
Distributed Run: True
NCCL avaliable: True
Using Device: cuda:0
GPU Memory Track | 03-Sep-20-14:21:41 | Total Used Memory:1470.7 Mb

FP16 Run: True
Dynamic Loss Scaling: True
cuDNN Enabled: True
cuDNN Benchmark: False
Distributed Run: True
NCCL avaliable: True
Using Device: cuda:0
Initializing Distributed
Initializing Distributed
Done initializing distributed.
Done initializing distributed.
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
DataSet Size: 9888
Loading checkpoint 'output_models/models/20200818-202109_3TTS_biaobei_ST_1e-4/checkpoint_newest'
DataSet Size: 9888
Loading checkpoint 'output_models/models/20200818-202109_3TTS_biaobei_ST_1e-4/checkpoint_newest'
2035501
Epoch: 27140
 2035501
Epoch: 27140
/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
^CTraceback (most recent call last):
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 239, in main
    process.wait()
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/zhiyuan.zhao/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by sjeaugey** [comment]
It seems wrong indeed to have process 136373 use both GPUs 1 and 2, so it seems to indicate that for some reason, some parts of PyTorch use GPU 1 while some other parts use GPU 2.

Also I'm not sure how `CUDA_VISIBLE_DEVICES=1,2` and `--gpu_names=1,2` interact with each other.

That said, it looks like a question for the PyTorch project, not NCCL.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
