### ISSUE TITLE
Multi-machine training torch hang on A100 

### ISSUE THREAD

**Issue by Richie-yan** [NVIDIA/nccl#537]
I trained the resnet50 model of torch on multiple A100 nodes. The communication framework used Horovod. I found that the model would hang after a few hundred steps. The gpu-util was 100%. 
Found hang on ncclallreduce through pstack. 
[resnet50-pstack.txt](https://github.com/NVIDIA/nccl/files/6855534/resnet50-pstack.txt)
The same code and image are normal when I run on a V100 machine and won’t hang. 
What might be the cause of the hang ncclallreduce?

cuda: 11.0
torch: 1.7 1.8
horovod: 0.19
nccl: 2.7.8 2.8.4 2.9.9
any advice can help me

**Comment by sjeaugey** [comment]
Is this reproducible? Does it happen randomly or always at the same point?

Also would there be any `WARN` in the log with `NCCL_DEBUG=WARN`?

**Comment by AddyLaddy** [comment]
Can you tell us any more about the node configuration and networking of this system?
Is it a DGX-A100 system?
At what scale is the job being run?
Can you see if there are any errors being reported by running it again with `NCCL_DEBUG=INFO`
When I took a quick glance at the stack trace I saw;

```
8  0x00007f6939a424f3 in cuLaunchKernel () from /usr/local/nvidia/cpu_lib/libcuda.so.1
#9  0x00007f6b2e8057cb in cudart::cudaApiLaunchKernel(void const*, dim3, dim3, void**, unsigned long, CUstream_st*) () from /usr/local/cuda/lib64/libnccl.so.2
#10 0x00007f6b2e847596 in cudaLaunchKernel () from /usr/local/cuda/lib64/libnccl.so.2
#11 0x00007f6b2e7b0015 in ncclBarrierEnqueueWait (comm=0x7f6727bcac30) at enqueue.cc:215
#12 0x00007f6b2e7b0be2 in ncclEnqueueCheck (info=0x7f694f4ab930) at enqueue.cc:565
#13 0x00007f6b2e7c86c0 in ncclAllReduce (sendbuff=0x7f68c51f6c00, recvbuff=<optimized out>, count=<optimized out>, datatype=ncclFloat32, op=<optimized out>, comm=<optimized out>, stream=0x7f694be78760) at collectives/all_reduce.cc:16
#14 0x00007f69a3e0df6b in horovod::common::NCCLAllreduce::Execute (this=0x7f694bb30f40, entries=..., response=...) at horovod/common/ops/nccl_operations.cc:144
#15 0x00007f69a3db6b01 in horovod::common::OperationManager::ExecuteAllreduce (this=this@entry=0x7f694b72a110, entries=..., response=...) at horovod/common/ops/operation_manager.cc:41
#16 0x00007f69a3db6f51 in horovod::common::OperationManager::ExecuteOperation (this=0x7f694b72a110, entries=..., response=...) at horovod/common/ops/operation_manager.cc:90
#17 0x00007f69a3d92803 in PerformOperation (state=..., response=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at horovod/common/operations.cc:300
#18 RunLoopOnce (state=...) at horovod/common/operations.cc:592
#19 horovod::common::(anonymous namespace)::BackgroundThreadLoop (state=...) at horovod/common/operations.cc:514
```

So it actually looks like NCCL is blocked in a CUDA call `cuLaunchKernel ` called from NCCL AllReduce.
Is the CUDA driver up to date with the CUDA11 release?

**Comment by Richie-yan** [comment]
> Can you tell us any more about the node configuration and networking of this system?
> Is it a DGX-A100 system?
> At what scale is the job being run?
> Can you see if there are any errors being reported by running it again with `NCCL_DEBUG=INFO`
> When I took a quick glance at the stack trace I saw;
> 
> ```
> 8  0x00007f6939a424f3 in cuLaunchKernel () from /usr/local/nvidia/cpu_lib/libcuda.so.1
> #9  0x00007f6b2e8057cb in cudart::cudaApiLaunchKernel(void const*, dim3, dim3, void**, unsigned long, CUstream_st*) () from /usr/local/cuda/lib64/libnccl.so.2
> #10 0x00007f6b2e847596 in cudaLaunchKernel () from /usr/local/cuda/lib64/libnccl.so.2
> #11 0x00007f6b2e7b0015 in ncclBarrierEnqueueWait (comm=0x7f6727bcac30) at enqueue.cc:215
> #12 0x00007f6b2e7b0be2 in ncclEnqueueCheck (info=0x7f694f4ab930) at enqueue.cc:565
> #13 0x00007f6b2e7c86c0 in ncclAllReduce (sendbuff=0x7f68c51f6c00, recvbuff=<optimized out>, count=<optimized out>, datatype=ncclFloat32, op=<optimized out>, comm=<optimized out>, stream=0x7f694be78760) at collectives/all_reduce.cc:16
> #14 0x00007f69a3e0df6b in horovod::common::NCCLAllreduce::Execute (this=0x7f694bb30f40, entries=..., response=...) at horovod/common/ops/nccl_operations.cc:144
> #15 0x00007f69a3db6b01 in horovod::common::OperationManager::ExecuteAllreduce (this=this@entry=0x7f694b72a110, entries=..., response=...) at horovod/common/ops/operation_manager.cc:41
> #16 0x00007f69a3db6f51 in horovod::common::OperationManager::ExecuteOperation (this=0x7f694b72a110, entries=..., response=...) at horovod/common/ops/operation_manager.cc:90
> #17 0x00007f69a3d92803 in PerformOperation (state=..., response=<error reading variable: access outside bounds of object referenced via synthetic pointer>) at horovod/common/operations.cc:300
> #18 RunLoopOnce (state=...) at horovod/common/operations.cc:592
> #19 horovod::common::(anonymous namespace)::BackgroundThreadLoop (state=...) at horovod/common/operations.cc:514
> ```
> 
> So it actually looks like NCCL is blocked in a CUDA call `cuLaunchKernel ` called from NCCL AllReduce.
> Is the CUDA driver up to date with the CUDA11 release?

Hi, thank you for your reply
My network uses ROCE， system is not DGX-A100 system
This phenomenon is reproduced stably, and 16 gpus in two nodes can be reproduced
The log of nccl looks normal and no abnormal error is reported. This is also a bit more puzzled for me.
It looks like nccl can’t get the cuda resources and it’s hang, but it’s not clear why it is related to the use of rdma.
What do you think might be the possible reason?

**Comment by Richie-yan** [comment]
Hi @sjeaugey @AddyLaddy 
Add two test results:
1. In the case of using a single network NIC -x NCCL_IB_HCA=mlx5_1:1, using GDR multiple nodes will not get stuck 
2. When using 8 network NICs, configure -x NCCL_PROTO=^LL128 and multiple nodes will not get stuck

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
