### ISSUE TITLE
Can we do distributed data parallel on GPU A100？

### ISSUE THREAD

**Issue by ljz756245026** [NVIDIA/nccl#570]
I meet the problem 
If I use pytorch version 1.9.0 with cu10.2, There are problem as follows:
```
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370156314/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

```

Then I use the newest pytorch version 1.9.1 and cu10.2/cu11.1. There are .cuda problem.When I run code like  ``` model.cuda(args.gpu)``` such problem happened.
```
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream
```

Whether GPU A100 do not support doing distributed data parallel?

**Comment by sjeaugey** [comment]
For the first error, it would be useful to set `NCCL_DEBUG=WARN` (or even `NCCL_DEBUG=INFO` for the full log), to get a clear message from NCCL of why it is failing.

For the second error, this doesn't seem like a NCCL error, so it would probably be a question to ask to PyTorch.

**Comment by ajtulloch** [comment]
That error suggests you seem to be enabling CUDA graphs.

**Comment by ljz756245026** [comment]
> For the first error, it would be useful to set `NCCL_DEBUG=WARN` (or even `NCCL_DEBUG=INFO` for the full log), to get a clear message from NCCL of why it is failing.
> 
> For the second error, this doesn't seem like a NCCL error, so it would probably be a question to ask to PyTorch.



the following is a .environ file. Before running the code , I have run ``` source .environ```
```
export NCCL_SOCKET_IFNAME=ens160 # NCCL_SOCKET_IFNAME
export NCCL_DEBUG=INFO
export NCCL_DEBUG=WARN
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
export CUDA_LAUNCH_BLOCKING=1

```
When I try to run data parallel on single machine with 2 GPUs, the following error happened.
NCCL version 2.7.8+cuda11.0


```
xxxxx:2573:2612 [1] graph/xml.cc:332 NCCL WARN Could not find real path of /sys/class/pci_bus/0000:1e/../../0000:1e:00.0

xxxxx:2572:2610 [0] graph/xml.cc:332 NCCL WARN Could not find real path of /sys/class/pci_bus/0000:1e/../../0000:1e:00.0
Traceback (most recent call last):
  File "main_ddp.py", line 285, in <module>
    main()
  File "main_ddp.py", line 123, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/liujz1/GraphSAGE/main_ddp.py", line 146, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/liujz1/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370156314/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8

exit status 1
```

**Comment by sjeaugey** [comment]
As commented on #573, you might be missing /sys in your environment. Other than that, can you explain why you set the below environment variables?
```
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
export CUDA_LAUNCH_BLOCKING=1
```
Also note, NCCL_DEBUG can only have one value so it's either WARN or INFO (the `NCCL_DEBUG=WARN` line is overriding the `NCCL_DEBUG=INFO` line in your `.environ` file).

**Comment by ljz756245026** [comment]
> As commented on #573, you might be missing /sys in your environment. Other than that, can you explain why you set the below environment variables?
> 
> ```
> export NCCL_IB_DISABLE=1
> export NCCL_P2P_DISABLE=1
> export CUDA_LAUNCH_BLOCKING=1
> ```
> 
> Also note, NCCL_DEBUG can only have one value so it's either WARN or INFO (the `NCCL_DEBUG=WARN` line is overriding the `NCCL_DEBUG=INFO` line in your `.environ` file).

for 
```
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
```
I got the answering from the below link(https://github.com/PyTorchLightning/pytorch-lightning/issues/4420#issuecomment-919856999).  In fact, I was running DDP successfully on 2 machines with TITAN(2 GPU) and Quadro(2 GPU). I want to transfer the code I used before to a 2 A100 GPU machine. However, it is unsuccessful.

for ``` export CUDA_LAUNCH_BLOCKING=1 ```, I want to get more detail error information, so I add this command.

**Comment by sjeaugey** [comment]
NCCL_IB_DISABLE=1 is useful if the IB connection establishment fails. For example, when you have IB cards but they are not functional.
NCCL_P2P_DISABLE=1 is useful if P2P fails when trying to enable P2P because of some corner case.

So while it's probably not affecting your issue much, it would be good to avoid setting those environment variables to avoid interactions.

Still, thanks for bringing my attention to that issue. I see a lot of unrelated issues and it needs to be clarified.

For your case, let's solve the /sys issue and see where it goes.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
