### ISSUE TITLE
[Bug report]Connection closed when using nccl to send pytorch tensor to different machine

### ISSUE THREAD

**Issue by HaoKang-Timmy** [NVIDIA/nccl#690]
Hi, I am using `nccl` backend `dist.send` and `dist.recv` to perform multi node training on seperate machines. But I got system call failed during the process.
Here is the minimal reproduce code
Client
```
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

def main():
    mp.spawn(main_worker, nprocs=1, args=(2,))
    



def main_worker(rank,n):
    print("begin ")
    dist.init_process_group(backend = 'nccl', init_method='tcp://xx.xx.x.30:23456',
                        rank=1, world_size=2)
    print(rank)
    
    
    input = torch.rand([10,10]).to(1)
    dist.recv(input,0)
    print("finish")


if __name__ == '__main__':
    main()
```
And here is the server
```
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

def main():
    mp.spawn(main_worker, nprocs=1, args=(2,))
    



def main_worker(rank,n):
    print("begin 0")
    dist.init_process_group(backend = 'nccl', init_method='tcp://xx.xx.x.30:23456',
                        rank=0, world_size=2)
    print(rank)

    input = torch.rand([10,10]).to(0)
    dist.send(input,1)

if __name__ == '__main__':
    main()
```
They could initialize but can not send and recv
The result(error) is
Client
```
begin 
0
x1:870114:870114 [1] NCCL INFO Bootstrap : Using eno1:xx.xx.x.xx<0>
x1:870114:870114 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
x1:870114:870114 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
x1:870114:870114 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB eno1:xx.xx.x.16<0>
x1:870114:870114 [1] NCCL INFO Using network IB
x1:870114:870206 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
x1:870114:870206 [1] NCCL INFO Setting affinity for GPU 1 to 3ff003ff
x1:870114:870206 [1] NCCL INFO Channel 00 : 0[5000] -> 1[3000] [receive] via NET/IB/0
x1:870114:870206 [1] NCCL INFO Channel 01 : 0[5000] -> 1[3000] [receive] via NET/IB/0
x1:870114:870206 [1] NCCL INFO Channel 00 : 1[3000] -> 0[5000] [send] via NET/IB/0
x1:870114:870206 [1] NCCL INFO Channel 01 : 1[3000] -> 0[5000] [send] via NET/IB/0

x1:870114:870206 [1] include/socket.h:423 NCCL WARN Net : Connection closed by remote peer xx.xx.x.30<45376>
x1:870114:870206 [1] NCCL INFO include/socket.h:445 -> 2
x1:870114:870206 [1] NCCL INFO include/socket.h:457 -> 2
x1:870114:870206 [1] NCCL INFO transport/net_ib.cc:505 -> 2
x1:870114:870206 [1] NCCL INFO include/net.h:22 -> 2
x1:870114:870206 [1] NCCL INFO transport/net.cc:234 -> 2
x1:870114:870206 [1] NCCL INFO transport.cc:119 -> 2
x1:870114:870206 [1] NCCL INFO init.cc:778 -> 2
x1:870114:870206 [1] NCCL INFO init.cc:904 -> 2
x1:870114:870206 [1] NCCL INFO group.cc:72 -> 2 [Async thread]
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    main()
  File "test.py", line 6, in main
    mp.spawn(main_worker, nprocs=1, args=(2,))
  File "/home/haokang/miniconda3/envs/3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/haokang/miniconda3/envs/3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/haokang/miniconda3/envs/3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/haokang/miniconda3/envs/3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/NFS/home/haokang/test.py", line 23, in main_worker
    dist.recv(input,0)
  File "/home/haokang/miniconda3/envs/3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1002, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
```
Server
```
begin 0
0
x0:26431:26431 [0] NCCL INFO Bootstrap : Using enp14s0:0:xx.xx.x.30<0>
x0:26431:26431 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

x0:26431:26431 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
x0:26431:26431 [0] NCCL INFO NET/Socket : Using [0]enp14s0:0:xx.xx.x.30<0> [1]lxdbr0:10.192.229.1<0> [2]br-a2bb5c34e1e1:172.18.0.1<0> [3]vethVPT6RK:fe80::fc8b:a2ff:fe77:b6d0%vethVPT6RK<0> [4]vethf00825f:fe80::5811:50ff:fe0f:65b6%vethf00825f<0> [5]veth88c9646:fe80::18b8:e8ff:feaf:7b41%veth88c9646<0> [6]veth6755258:fe80::7c74:71ff:fe97:44dc%veth6755258<0>
x0:26431:26431 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda10.2
x0:26431:26608 [0] NCCL INFO Channel 00/02 :    0   1
x0:26431:26608 [0] NCCL INFO Channel 01/02 :    0   1
x0:26431:26608 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
x0:26431:26608 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
x0:26431:26608 [0] NCCL INFO Channel 00 : 1[3000] -> 0[5000] [receive] via NET/Socket/0
x0:26431:26608 [0] NCCL INFO Channel 01 : 1[3000] -> 0[5000] [receive] via NET/Socket/0
x0:26431:26608 [0] NCCL INFO Channel 00 : 0[5000] -> 1[3000] [send] via NET/Socket/0
x0:26431:26608 [0] NCCL INFO Channel 01 : 0[5000] -> 1[3000] [send] via NET/Socket/0
x0:26431:26608 [0] NCCL INFO Connected all rings
x0:26431:26608 [0] NCCL INFO Connected all trees
x0:26431:26608 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
x0:26431:26608 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
x0:26431:26608 [0] NCCL INFO comm 0x7efec4001200 rank 0 nranks 2 cudaDev 0 busId 5000 - Init COMPLETE
x0:26431:26431 [0] NCCL INFO Launch mode Parallel
```
It seems that something was wrong with client
When I print the debug info

```
x1:947320:947407 [1] include/socket.h:423 NCCL WARN Net : Connection closed by remote peer 
```

**Comment by sjeaugey** [comment]
On the client:
```
x1:870114:870114 [1] NCCL INFO Using network IB
```
On the server:
```
x0:26431:26431 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
[...]
x0:26431:26431 [0] NCCL INFO Using network Socket
```
That's probably the reason for the error. Each side is trying to use a different network.

**Comment by LowSh** [comment]
> [0] node0:13571:13571 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[0] node0:13571:13571 [0] NCCL INFO Bootstrap : Using enp10s0:10.10.7.107<0>
[0] node0:13571:13571 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
[0] node0:13571:13571 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
[1] node2:22555:22555 [0] NCCL INFO cudaDriverVersion 11070
[3] node2:22556:22556 [1] NCCL INFO cudaDriverVersion 11070
[1] node2:22555:22555 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[3] node2:22556:22556 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[1] node2:22555:22555 [0] NCCL INFO Bootstrap : Using enp10s0:10.10.7.109<0>
[3] node2:22556:22556 [1] NCCL INFO Bootstrap : Using enp10s0:10.10.7.109<0>
[1] node2:22555:22555 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
[3] node2:22556:22556 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
[3] node2:22556:22556 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
[1] node2:22555:22555 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
[2] node0:13572:13572 [1] NCCL INFO cudaDriverVersion 11070
[2] node0:13572:13572 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[0] node0:13571:13571 [0] NCCL INFO cudaDriverVersion 11070
[0] NCCL version 2.18.3+cuda11.0
[2] node0:13572:13572 [1] NCCL INFO Bootstrap : Using enp10s0:10.10.7.107<0>
[2] node0:13572:13572 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
[2] node0:13572:13572 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
[1] node2:22555:22555 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[1] node2:22555:22555 [0] NCCL INFO NET/IB : No device found.
[1] node2:22555:22555 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[1] node2:22555:22555 [0] NCCL INFO NET/Socket : Using [0]enp10s0:10.10.7.109<0>
[1] node2:22555:22555 [0] NCCL INFO Using network Socket
[3] node2:22556:22556 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[3] node2:22556:22556 [1] NCCL INFO NET/IB : No device found.
[3] node2:22556:22556 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[3] node2:22556:22556 [1] NCCL INFO NET/Socket : Using [0]enp10s0:10.10.7.109<0>
[3] node2:22556:22556 [1] NCCL INFO Using network Socket
[2] node0:13572:13572 [1] NCCL INFO Failed to open libibverbs.so[.1]
[2] node0:13572:13572 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[2] node0:13572:13572 [1] NCCL INFO NET/Socket : Using [0]enp10s0:10.10.7.107<0>
[2] node0:13572:13572 [1] NCCL INFO Using network Socket
[0] node0:13571:13571 [0] NCCL INFO Failed to open libibverbs.so[.1]
[0] node0:13571:13571 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
[0] node0:13571:13571 [0] NCCL INFO NET/Socket : Using [0]enp10s0:10.10.7.107<0>
[0] node0:13571:13571 [0] NCCL INFO Using network Socket
[3] node2:22556:22556 [1] NCCL INFO comm 0x54804320 rank 3 nranks 4 cudaDev 1 nvmlDev 1 busId 2000 commId 0x6945a26e4e09a5c0 - Init START
[0] node0:13571:13571 [0] NCCL INFO comm 0x56105c1a0450 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0x6945a26e4e09a5c0 - Init START
[1] node2:22555:22555 [0] NCCL INFO comm 0x55c136f0 rank 1 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0x6945a26e4e09a5c0 - Init START
[2] node0:13572:13572 [1] NCCL INFO comm 0x5578c5b405e0 rank 2 nranks 4 cudaDev 1 nvmlDev 1 busId 2000 commId 0x6945a26e4e09a5c0 - Init START
[0] node0:13571:13571 [0] NCCL INFO Channel 00/02 :    0   2   1   3
[0] node0:13571:13571 [0] NCCL INFO Channel 01/02 :    0   2   1   3
[0] node0:13571:13571 [0] NCCL INFO Trees [0] 2/1/-1->0->-1 [1] 2/-1/-1->0->1
[0] node0:13571:13571 [0] NCCL INFO P2P Chunksize set to 131072
[1] node2:22555:22555 [0] NCCL INFO Trees [0] 3/-1/-1->1->0 [1] 3/0/-1->1->-1
[1] node2:22555:22555 [0] NCCL INFO P2P Chunksize set to 131072
[2] node0:13572:13572 [1] NCCL INFO Trees [0] -1/-1/-1->2->0 [1] -1/-1/-1->2->0
[2] node0:13572:13572 [1] NCCL INFO P2P Chunksize set to 131072
[3] node2:22556:22556 [1] NCCL INFO Trees [0] -1/-1/-1->3->1 [1] -1/-1/-1->3->1
[3] node2:22556:22556 [1] NCCL INFO P2P Chunksize set to 131072
[1] node2:22555:22555 [0] NCCL INFO Channel 00 : 1[0] -> 3[1] via SHM/direct/direct
[1] node2:22555:22555 [0] NCCL INFO Channel 01 : 1[0] -> 3[1] via SHM/direct/direct
[0] node0:13571:13571 [0] NCCL INFO Channel 00/0 : 3[1] -> 0[0] [receive] via NET/Socket/0
[0] node0:13571:13571 [0] NCCL INFO Channel 01/0 : 3[1] -> 0[0] [receive] via NET/Socket/0
[3] node2:22556:22556 [1] NCCL INFO Channel 00/0 : 3[1] -> 0[0] [send] via NET/Socket/0
[3] node2:22556:22556 [1] NCCL INFO Channel 01/0 : 3[1] -> 0[0] [send] via NET/Socket/0
[0] node0:13571:13571 [0] NCCL INFO Channel 00 : 0[0] -> 2[1] via SHM/direct/direct
[0] node0:13571:13571 [0] NCCL INFO Channel 01 : 0[0] -> 2[1] via SHM/direct/direct
[2] node0:13572:13572 [1] NCCL INFO Channel 00/0 : 2[1] -> 1[0] [send] via NET/Socket/0
[2] node0:13572:13572 [1] NCCL INFO Channel 01/0 : 2[1] -> 1[0] [send] via NET/Socket/0
[3] node2:22556:22556 [1] NCCL INFO Connected all rings
[3] node2:22556:22556 [1] NCCL INFO Channel 00 : 3[1] -> 1[0] via SHM/direct/direct
[3] node2:22556:22556 [1] NCCL INFO Channel 01 : 3[1] -> 1[0] via SHM/direct/direct
[0] node0:13571:13571 [0] NCCL INFO Connected all rings
[0] node0:13571:13571 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [send] via NET/Socket/0
[0] node0:13571:13571 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [send] via NET/Socket/0
[1] node2:22555:22555 [0] NCCL INFO Channel 00/0 : 2[1] -> 1[0] [receive] via NET/Socket/0
[1] node2:22555:22555 [0] NCCL INFO Channel 01/0 : 2[1] -> 1[0] [receive] via NET/Socket/0
[1] node2:22555:22555 [0] NCCL INFO Connected all rings
[1] node2:22555:22555 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [receive] via NET/Socket/0
[1] node2:22555:22555 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [receive] via NET/Socket/0
[2] node0:13572:13572 [1] NCCL INFO Connected all rings
[2] node0:13572:13572 [1] NCCL INFO Channel 00 : 2[1] -> 0[0] via SHM/direct/direct
[2] node0:13572:13572 [1] NCCL INFO Channel 01 : 2[1] -> 0[0] via SHM/direct/direct
[1] node2:22555:22555 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [send] via NET/Socket/0
[1] node2:22555:22555 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [send] via NET/Socket/0
[3] node2:22556:22556 [1] NCCL INFO Connected all trees
[3] node2:22556:22556 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
[3] node2:22556:22556 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
[0] node0:13571:13571 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
[0] node0:13571:13571 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
[2] node0:13572:13572 [1] NCCL INFO Connected all trees
[2] node0:13572:13572 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
[2] node0:13572:13572 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
[1] node2:22555:22555 [0] NCCL INFO Connected all trees
[1] node2:22555:22555 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
[1] node2:22555:22555 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
[0] node0:13571:13571 [0] NCCL INFO Connected all trees
[0] node0:13571:13571 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
[0] node0:13571:13571 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
[1] node2:22555:22555 [0] NCCL INFO comm 0x55c136f0 rank 1 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0x6945a26e4e09a5c0 - Init COMPLETE
[3] node2:22556:22556 [1] NCCL INFO comm 0x54804320 rank 3 nranks 4 cudaDev 1 nvmlDev 1 busId 2000 commId 0x6945a26e4e09a5c0 - Init COMPLETE
[0] node0:13571:13571 [0] NCCL INFO comm 0x56105c1a0450 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0x6945a26e4e09a5c0 - Init COMPLETE
[2] node0:13572:13572 [1] NCCL INFO comm 0x5578c5b405e0 rank 2 nranks 4 cudaDev 1 nvmlDev 1 busId 2000 commId 0x6945a26e4e09a5c0 - Init COMPLETE
[3] vqnet2.12.0
[3] node2
[3] rank 3  [[0.411529 ,0.0140784,0.7926515,0.5860262,0.0432614]] before
[3] rank 3  [[0.,0.,0.,0.,0.]] after
[1] recv group0
[0] send group0
[2] vqnet2.12.0
[2] node0
[2] rank 2  [[0.2120169,0.4495008,0.4716017,0.1913168,0.2148147]] before
[2] rank 2  [[0.,0.,0.,0.,0.]] after
[0] 
[0] node0:13571:13857 [0] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer node2<42830>
[0] node0:13571:13857 [0] NCCL INFO misc/socket.cc:57 -> 6
[0] node0:13571:13857 [0] NCCL INFO misc/socket.cc:786 -> 6
[0] node0:13571:13857 [0] NCCL INFO bootstrap.cc:71 -> 6
[0] node0:13571:13857 [0] NCCL INFO bootstrap.cc:395 -> 6
[0] node0:13571:13857 [0] NCCL INFO init.cc:1283 -> 6
[0] node0:13571:13857 [0] NCCL INFO init.cc:1342 -> 6
[0] node0:13571:13857 [0] NCCL INFO group.cc:65 -> 6 [Async thread]
[0] node0:13571:13571 [0] NCCL INFO group.cc:406 -> 6
[0] node0:13571:13571 [0] NCCL INFO group.cc:96 -> 6
[0] Failed, NCCL error /data/hao/vqnet/src/distributed/nccl_api.cpp:758 'remote process exited or there was a network error'
[1] 
[1] node2:22555:22817 [0] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer node0<57726>
[1] node2:22555:22817 [0] NCCL INFO misc/socket.cc:57 -> 6
[1] node2:22555:22817 [0] NCCL INFO misc/socket.cc:786 -> 6
[1] node2:22555:22817 [0] NCCL INFO bootstrap.cc:71 -> 6
[1] node2:22555:22817 [0] NCCL INFO bootstrap.cc:395 -> 6
[1] node2:22555:22817 [0] NCCL INFO init.cc:1283 -> 6
[1] node2:22555:22817 [0] NCCL INFO init.cc:1342 -> 6
[1] node2:22555:22817 [0] NCCL INFO group.cc:65 -> 6 [Async thread]
[1] node2:22555:22555 [0] NCCL INFO group.cc:406 -> 6
[1] node2:22555:22555 [0] NCCL INFO group.cc:96 -> 6
[1] Failed, NCCL error /data/hao/vqnet/src/distributed/nccl_api.cpp:801 'remote process exited or there was a network error'
