### ISSUE TITLE
Segmentation fault with nsys profiling in nccl 2.14.3

### ISSUE THREAD

**Issue by jhoareau** [NVIDIA/nccl#785]
This is happening in Pytorch 1.13.1, that uses nccl 2.14.3. 1.12.0 that uses nccl 2.10.3 does not have the problem. See Pytorch issue https://github.com/pytorch/pytorch/issues/94393 

Using the DDP sample code from Pytorch documentation (https://pytorch.org/tutorials/intermediate/ddp_tutorial.html):

```python
import os

import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP


def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def demo_basic(rank, world_size):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel().to(rank)
    ddp_model = DDP(model, device_ids=[rank])

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    optimizer.zero_grad()
    outputs = ddp_model(torch.randn(20, 10))
    labels = torch.randn(20, 5).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()

    cleanup()


def run_demo(demo_fn, world_size):
    mp.start_processes(demo_fn,
             args=(world_size,),
             nprocs=world_size,
             join=True,
             start_method="fork")

if __name__ == "__main__":
    run_demo(demo_basic, torch.cuda.device_count())
```

When running this script with Pytorch 1.13.1+cu117, using nsys 2023.1.1:

`nsys profile python test_ddp.py` yields:
```
Traceback (most recent call last):
  File "test_ddp.py", line 59, in <module>
    run_demo(demo_basic, torch.cuda.device_count())
  File "test_ddp.py", line 53, in run_demo
    mp.spawn(demo_fn,
  File "torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
```

The standalone script is running fine.

When running this script with Pytorch 1.12.0+cu116:

Both the `nsys profile python test_ddp.py` and standalone scripts yield:
```
Running basic DDP example on rank 1.
Running basic DDP example on rank 0.
```

Some extra logging with NCCL_DEBUG=INFO that could help debug the issue:

In Pytorch 1.13.1+cu117:
```
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I socket.cpp:442] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:492] [c10d - debug] The server socket is attempting to listen on [::]:12355.
[I socket.cpp:566] [c10d] The server socket has started to listen on [::]:12355.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46560.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46560.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46570.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46570.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46578.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46578.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46590.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46590.
[I ProcessGroupNCCL.cpp:642] [Rank 1] NCCL_DESYNC_DEBUG and NCCL_ASYNC_ERROR_HANDLING must both be enabled. Enabling NCCL_ASYNC_ERROR_HANDLING.
[I ProcessGroupNCCL.cpp:669] [Rank 1] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 1
NCCL_DESYNC_DEBUG: 1
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:835] [Rank 1] NCCL watchdog thread started!
[I ProcessGroupNCCL.cpp:642] [Rank 0] NCCL_DESYNC_DEBUG and NCCL_ASYNC_ERROR_HANDLING must both be enabled. Enabling NCCL_ASYNC_ERROR_HANDLING.
[I ProcessGroupNCCL.cpp:669] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 1
NCCL_DESYNC_DEBUG: 1
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:835] [Rank 0] NCCL watchdog thread started!
cph-testbench:352272:352272 [0] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:352272:352272 [0] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:352272:352272 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.14.3+cuda11.7
cph-testbench:352272:352272 [0] NCCL INFO init.cc:1147 Cuda Host Alloc Size 4 pointer 0x7f0543200000
Traceback (most recent call last):
  File "test_ddp.py", line 62, in <module>
    run_demo(demo_basic, world_size)
  File "test_ddp.py", line 53, in run_demo
    mp.spawn(demo_fn,
  File "torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
```

In Pytorch 1.12.0+cu116:
```
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:710] [c10d - trace] The server socket on [::ffff:127.0.0.1]:12355 is not yet listening (errno: 111 - Connection refused), will retry.
[I socket.cpp:417] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:462] [c10d - debug] The server socket is attempting to listen on [::]:12355.
[I socket.cpp:522] [c10d] The server socket has started to listen on [::]:12355.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51350.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51350.
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51360.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51360.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51372.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51372.
[I ProcessGroupNCCL.cpp:587] [Rank 1] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_DESYNC_DEBUG: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:751] [Rank 1] NCCL watchdog thread started!
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51374.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51374.
[I ProcessGroupNCCL.cpp:587] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_DESYNC_DEBUG: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:751] [Rank 0] NCCL watchdog thread started!
cph-testbench:353117:353117 [0] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:353117:353117 [0] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:353117:353117 [0] NCCL INFO NET/IB : No device found.
cph-testbench:353117:353117 [0] NCCL INFO NET/Socket : Using [0]enp5s0:172.26.45.54<0> [1]br-7ef2ebc742b4:172.20.0.1<0> [2]br-929d72973484:172.18.0.1<0> [3]br-e2ff7a2944d2:172.19.0.1<0>
cph-testbench:353117:353117 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.6
cph-testbench:353118:353118 [1] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:353118:353118 [1] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:353118:353118 [1] NCCL INFO NET/IB : No device found.
cph-testbench:353118:353118 [1] NCCL INFO NET/Socket : Using [0]enp5s0:172.26.45.54<0> [1]br-7ef2ebc742b4:172.20.0.1<0> [2]br-929d72973484:172.18.0.1<0> [3]br-e2ff7a2944d2:172.19.0.1<0>
cph-testbench:353118:353118 [1] NCCL INFO Using network Socket
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 0(=a000) and dev 1(=41000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 0(=a000) and dev 1(=41000)
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
...
```

GDB stacktrace of the segv:
```
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007ff5c8b0f1da in ?? () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
No symbol table info available.
#2  0x00007ff5c885f606 in NSYS_DL_dlvsym () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
No symbol table info available.
#3  0x00007ff58be01168 in initOnceFunc () at misc/ibvwrap.cc:94
        ibvhandle = 0x7ff518002d30
        tmp = <optimized out>
        cast = 0x7ff59acdfb08 <ibv_internal_reg_dmabuf_mr>
        __func__ = "initOnceFunc"
#4  0x00007ff5c83ae4df in __pthread_once_slow (once_control=0x7ff59acdfba4 <initOnceControl>, init_routine=0x7ff58be00ec0 <initOnceFunc()>) at pthread_once.c:116
        _buffer = {__routine = 0x7ff5c83ae530 <clear_once_control>, __arg = 0x7ff59acdfba4 <initOnceControl>, __canceltype = 0, __prev = 0x0}
        val = <optimized out>
        newval = <optimized out>
#5  0x00007ff5c83ae595 in __GI___pthread_once (once_control=once_control@entry=0x7ff59acdfba4 <initOnceControl>, init_routine=init_routine@entry=0x7ff58be00ec0 <initOnceFunc()>) at pthread_once.c:143
        val = <optimized out>
#6  0x00007ff58be01847 in wrap_ibv_symbols () at misc/ibvwrap.cc:139
No locals.
#7  0x00007ff58bde3349 in ncclIbInit (logFunction=<optimized out>) at transport/net_ib.cc:150
        shownIbHcaEnv = 0
        __func__ = <optimized out>
        nIbDevs = <optimized out>
        devices = <optimized out>
        userIbEnv = <optimized out>
        userIfs = <optimized out>
        searchNot = <optimized out>
        searchExact = <optimized out>
        nUserIfs = <optimized out>
        d = <optimized out>
        context = <optimized out>
        nPorts = <optimized out>
        devAttr = <optimized out>
        port = <optimized out>
        portAttr = <optimized out>
        res = <optimized out>
        line = <optimized out>
        addrline = <optimized out>
        d = <optimized out>
#8  0x00007ff58bdbb84a in netGetState (state=<synthetic pointer>, i=1) at net.cc:245
        ndev = 32757
#9  ncclNetInit (comm=comm@entry=0x555d647315b0) at net.cc:273
        res = <optimized out>
        state = <optimized out>
        i = 1
        netName = <optimized out>
        ok = false
        __func__ = <optimized out>
#10 0x00007ff58bd7e687 in commAlloc (comret=comret@entry=0x555d64123530, ndev=ndev@entry=1, rank=rank@entry=0) at init.cc:323
        res = <optimized out>
        comm = 0x555d647315b0
        __func__ = "commAlloc"
#11 0x00007ff58bd8363e in ncclCommInitRankFunc (job_=<optimized out>) at init.cc:1088
        job = <optimized out>
        newcomm = 0x555d64123530
        comm = 0x555d647315b0
        nranks = 1
        commId = {internal = "\002\000\245\355\254\032-6", '\000' <repeats 119 times>}
        myrank = 0
        cudaDev = <optimized out>
        res = ncclSuccess
        __func__ = "ncclCommInitRankFunc"
#12 0x00007ff58bd7bd68 in ncclAsyncJobMain (arg=0x555d29662100) at group.cc:62
        job = 0x555d29662100
        __func__ = "ncclAsyncJobMain"
#13 0x00007ff5c88b4c0d in ?? () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
No symbol table info available.
#14 0x00007ff5c83a5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140691213436672, 2100541623046917983, 140732780327214, 140732780327215, 140732780327216, 140691213434304, -2104046464448442529, -2104008895042138273}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#15 0x00007ff5c816e133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

I see you have suggested dynamically linking a different version of nccl to pytorch in another recent but possibly related issue, and I will give that a shot in the coming days.

**Comment by jhoareau** [comment]
The issue is fully in Nsight Systems - see https://forums.developer.nvidia.com/t/profiling-nccl-2-14-3-leads-to-segmentation-fault/242371/6
