### ISSUE TITLE
RuntimeError: [Rank 0]: Ranks 4, 5, 6, 7 failed to pass monitoredBarrier in 2000000 ms

### ISSUE THREAD

**Issue by monajalal** [NVIDIA/nccl#849]
I changed the timeout to 33 min from default of 30 min. Why am I facing this problem? isn't 33 min for timeout anyways so much? I am using NCCL backend for DistributedDataParallel in PyTorch.

```
CPython
3.8.10
uname_result(system='Linux', node=number', release='5.15.0-1029-azure', version='#36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022', machine='x86_64', processor='x86_64')
System information: Linux #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022
Python version: 3.8.10
MLflow version: 2.3.2
MLflow module location: /usr/local/lib/python3.8/dist-packages/mlflow/__init__.py
Tracking URI:URI
Registry URI: URI
MLflow environment variables: 
  MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING: True
  MLFLOW_EXPERIMENT_ID: 021dec90-c7d3-4233-813e-799d15e43f9a
  MLFLOW_EXPERIMENT_NAME: dev_DOPE_FAT_test2
  MLFLOW_RUN_ID: 54be70c6-c1a9-4433-8943-e1678667884b
  MLFLOW_TRACKING_TOKEN: token
  MLFLOW_TRACKING_URI: URI
MLflow dependencies: 
  Flask: 2.3.2
  Jinja2: 3.1.2
  alembic: 1.11.1
  click: 8.1.3
  cloudpickle: 2.2.0
  databricks-cli: 0.17.7
  docker: 6.1.2
  entrypoints: 0.4
  gitpython: 3.1.31
  gunicorn: 20.1.0
  importlib-metadata: 5.1.0
  markdown: 3.4.1
  matplotlib: 3.7.0
  numpy: 1.24.2
  packaging: 22.0
  pandas: 1.5.2
  protobuf: 3.20.1
  pyarrow: 9.0.0
  pytz: 2022.6
  pyyaml: 6.0
  querystring-parser: 1.2.4
  requests: 2.28.1
  scikit-learn: 0.24.2
  scipy: 1.10.1
  sqlalchemy: 2.0.15
  sqlparse: 0.4.4
2023/05/23 15:48:00 WARNING mlflow.tracking.fluent: Exception raised while enabling autologging for sklearn: No module named 'sklearn.utils.testing'
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.4<0>
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin (v5)
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v5)
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO cudaDriverVersion 11040
NCCL version 2.14.3+cuda11.7
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO P2P plugin IBext
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/IB : No device found.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.4<0>
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Using network Socket
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/6045bd7e-6943-6045-bd7e-69436045bd7e is not a PCI device (vmbus). Attaching to first CPU
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO === System : maxBw 5.0 totalBw 12.0 ===
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO CPU/0 (1/1/1)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[5000.0] - NIC/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO                 + NET[5.0] - NET/0 (0/0/5.000000)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/100000 (0)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/200000 (1)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/300000 (2)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO + PCI[12.0] - GPU/400000 (3)
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO ==========================================
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NET/0 :GPU/100000 (3/5.000000/PHB) GPU/200000 (3/5.000000/PHB) GPU/300000 (3/5.000000/PHB) GPU/400000 (3/5.000000/PHB) CPU/0 (2/5.000000/PHB) NET/0 (0/5000.000000/LOC) 
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, bw 5.000000/5.000000, type PHB/PHB, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 1, crossNic 0, nChannels 1, bw 6.000000/5.000000, type PHB/PHB, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, bw 0.000000/0.000000, type NVL/PIX, sameChannels 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/8/-1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Tree 1 : 4 -> 0 -> 1/-1/-1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Ring 00 : 15 -> 0 -> 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Ring 01 : 15 -> 0 -> 1
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Trees [0] 1/8/-1->0->-1 [1] 1/-1/-1->0->4
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via SHM/direct/direct
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01 : 0[100000] -> 1[200000] via SHM/direct/direct
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Connected all rings
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 0[100000] -> 4[100000] [send] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 8[100000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 00/0 : 0[100000] -> 8[100000] [send] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO Channel 01/0 : 4[100000] -> 0[100000] [receive] via NET/Socket/0
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NDownloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
training script path:  /mnt/azureml/cr/j/aa54f8a6f177420ea912cde147fec47b/exe/wd
start: 15:48:00.718630
object of interest is: cracker
manual seed set to 8346
opt.checkpoints = /mnt/azureml/cr/j/aa54f8a6f177420ea912cde147fec47b/cap/data-capability/wd/checkpoints
world size is:  16
global rank is 0 and local_rank is 0
is_distributed is True and batch_size is 1
os.getpid() is 39 and initializing process group with {'MASTER_ADDR': '10.0.0.4', 'MASTER_PORT': '6105', 'LOCAL_RANK': '0', 'RANK': '0', 'WORLD_SIZE': '16'}
device is cuda:0
load data
train data size:  246000
training data len:  246000
batch size is:  1
training data: 15375 batches
load models
torch.cuda.device_count():  4
type opt.gpuids: <class 'list'>
gpuids are: [0, 1, 2, 3]
Training network pretrained on imagenet.

  0%|          | 0.00/548M [00:00<?, ?B/s]
  1%|▏         | 7.99M/548M [00:00<00:08, 68.6MB/s]
  3%|▎         | 15.8M/548M [00:00<00:10, 51.2MB/s]
  4%|▍         | 20.9M/548M [00:00<00:13, 39.5MB/s]
  5%|▍         | 24.9M/548M [00:00<00:16, 34.3MB/s]
  6%|▌         | 32.0M/548M [00:00<00:13, 39.0MB/s]
  7%|▋         | 40.0M/548M [00:00<00:11, 46.8MB/s]
  9%|▉         | 48.0M/548M [00:01<00:10, 48.4MB/s]
 10%|█         | 56.0M/548M [00:01<00:09, 53.4MB/s]
 12%|█▏        | 64.0M/548M [00:01<00:11, 43.7MB/s]
 13%|█▎        | 73.4M/548M [00:01<00:09, 54.4MB/s]
 15%|█▍        | 82.1M/548M [00:01<00:07, 62.4MB/s]
 16%|█▌        | 88.9M/548M [00:01<00:07, 64.1MB/s]
 18%|█▊        | 99.7M/548M [00:01<00:06, 76.3MB/s]
 20%|█▉        | 108M/548M [00:02<00:06, 71.0MB/s] 
 21%|██        | 115M/548M [00:02<00:07, 62.2MB/s]
 22%|██▏       | 121M/548M [00:02<00:07, 58.7MB/s]
 23%|██▎       | 128M/548M [00:02<00:07, 57.9MB/s]
 24%|██▍       | 134M/548M [00:02<00:07, 57.5MB/s]
 25%|██▌       | 139M/548M [00:02<00:08, 48.1MB/s]
 26%|██▋       | 144M/548M [00:02<00:09, 45.8MB/s]
 27%|██▋       | 150M/548M [00:02<00:08, 49.6MB/s]
 28%|██▊       | 155M/548M [00:03<00:09, 45.7MB/s]
 29%|██▉       | 160M/548M [00:03<00:10, 39.9MB/s]
 30%|███       | 166M/548M [00:03<00:09, 43.9MB/s]
 31%|███       | 171M/548M [00:03<00:11, 33.9MB/s]
 32%|███▏      | 176M/548M [00:03<00:11, 34.3MB/s]
 34%|███▎      | 184M/548M [00:03<00:09, 41.3MB/s]
 35%|███▌      | 192M/548M [00:04<00:07, 47.2MB/s]
 36%|███▋      | 200M/548M [00:04<00:08, 42.2MB/s]
 38%|███▊      | 208M/548M [00:04<00:07, 49.4MB/s]
 39%|███▉      | 216M/548M [00:04<00:06, 55.3MB/s]
 41%|████      | 224M/548M [00:04<00:06, 51.2MB/s]
 42%|████▏     | 229M/548M [00:04<00:06, 49.5MB/s]
 43%|████▎     | 234M/548M [00:04<00:07, 45.7MB/s]
 44%|████▍     | 242M/548M [00:05<00:05, 54.3MB/s]
 45%|████▌     | 248M/548M [00:05<00:06, 49.8MB/s]
 47%|████▋     | 256M/548M [00:05<00:05, 57.9MB/s]
 48%|████▊     | 263M/548M [00:05<00:04, 61.7MB/s]
 49%|████▉     | 269M/548M [00:05<00:04, 59.4MB/s]
 50%|█████     | 275M/548M [00:05<00:05, 50.1MB/s]
 51%|█████     | 280M/548M [00:05<00:06, 40.8MB/s]
 53%|█████▎    | 288M/548M [00:06<00:05, 48.2MB/s]
 54%|█████▍    | 296M/548M [00:06<00:05, 52.5MB/s]
 55%|█████▌    | 302M/548M [00:06<00:05, 50.7MB/s]
 56%|█████▌    | 307M/548M [00:06<00:05, 44.8MB/s]
 57%|█████▋    | 312M/548M [00:06<00:05, 42.9MB/s]
 58%|█████▊    | 320M/548M [00:06<00:05, 47.1MB/s]
 60%|█████▉    | 328M/548M [00:06<00:04, 55.1MB/s]
 61%|██████    | 333M/548M [00:07<00:04, 50.8MB/s]
 62%|██████▏   | 338M/548M [00:07<00:04, 49.8MB/s]
 63%|██████▎   | 344M/548M [00:07<00:04, 48.4MB/s]
 64%|██████▍   | 352M/548M [00:07<00:03, 54.6MB/s]
 66%|██████▌   | 361M/548M [00:07<00:03, 63.8MB/s]
 67%|██████▋   | 368M/548M [00:07<00:03, 53.6MB/s]
 69%|██████▊   | 376M/548M [00:07<00:03, 52.0MB/s]
 70%|███████   | 384M/548M [00:07<00:03, 57.0MB/s]
 72%|███████▏  | 392M/548M [00:08<00:02, 55.6MB/s]
 73%|███████▎  | 400M/548M [00:08<00:02, 59.5MB/s]
 74%|███████▍  | 408M/548M [00:08<00:02, 65.7MB/s]
 76%|███████▌  | 417M/548M [00:08<00:01, 71.3MB/s]
 77%|███████▋  | 424M/548M [00:08<00:01, 70.7MB/s]
 79%|███████▉  | 432M/548M [00:08<00:01, 68.0MB/s]
 80%|████████  | 440M/548M [00:08<00:01, 71.3MB/s]
 82%|████████▏ | 448M/548M [00:08<00:01, 70.9MB/s]
 83%|████████▎ | 456M/548M [00:09<00:01, 73.8MB/s]
 85%|████████▍ | 464M/548M [00:09<00:01, 69.4MB/s]
 86%|████████▌ | 472M/548M [00:09<00:01, 68.7MB/s]
 88%|████████▊ | 480M/548M [00:09<00:01, 66.0MB/s]
 89%|████████▉ | 488M/548M [00:09<00:01, 55.9MB/s]
 91%|█████████ | 496M/548M [00:09<00:00, 58.0MB/s]
 92%|█████████▏| 504M/548M [00:09<00:00, 54.4MB/s]
 93%|█████████▎| 512M/548M [00:10<00:00, 58.0MB/s]
 94%|█████████▍| 518M/548M [00:10<00:00, 51.1MB/s]
 95%|█████████▌| 523M/548M [00:10<00:00, 46.4MB/s]
 97%|█████████▋| 533M/548M [00:10<00:00, 58.9MB/s]
 98%|█████████▊| 539M/548M [00:10<00:00, 59.1MB/s]
 99%|█████████▉| 545M/548M [00:10<00:00, 58.0MB/s]
100%|██████████| 548M/548M [00:10<00:00, 53.7MB/s]CCL INFO Connected all trees
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 512 | 512
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO NCCL_P2P_PXN_LEVEL set by environment to 0.
517cc60b90264a01ac05aafd5e6ca61e000000:39:295 [0] NCCL INFO comm 0x2bb6f090 rank 0 nranks 16 cudaDev 0 busId 100000 - Init COMPLETE
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 4 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 5 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 6 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:2803] [Rank 0]: Rank 7 failed to pass monitoredBarrier in 2000000 ms
[E ProcessGroupGloo.cpp:137] [Rank 0]: Ranks 4, 5, 6, 7 failed to pass monitoredBarrier in 2000000 ms

Traceback (most recent call last):
  File "train.py", line 1467, in <module>
    net = torch.nn.parallel.DistributedDataParallel(net, device_ids=[local_rank], output_device=local_rank) # do we need output_device=local_rank?
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 655, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/utils.py", line 112, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [Rank 0]: Ranks 4, 5, 6, 7 failed to pass monitoredBarrier in 2000000 ms
517cc60b90264a01ac05aafd5e6ca61e000000:39:304 [0] NCCL INFO [Service thread] Connection closed by localRank 0
517cc60b90264a01ac05aafd5e6ca61e000000:39:39 [0] NCCL INFO comm 0x2bb6f090 rank 0 nranks 16 cudaDev 0 busId 100000 - Abort COMPLETE
```

Here's the related part of the code. 

```
# DISTRIBUTED: this is required to initialize the pytorch backend
dist_url = "env://" # default
# dist_url = "auto"
dist.init_process_group(
    backend=distributed_backend,
    init_method=dist_url,
    timeout=datetime.timedelta(seconds=2000), #default is 30 min
    world_size=world_size,
    rank=world_rank  
)


torch.cuda.set_device(local_rank)
device = torch.device("cuda", local_rank) if torch.cuda.is_available() else 'cpu'
print("device is {}".format(device))
# this will make all .cuda() calls work properly

# synchronize all the threads to reach this point before moving on
dist.barrier() 

```

`Dockerfile`:
```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
# FROM nvcr.io/nvidia/pytorch:22.04-py3
#FROM nvcr.io/nvidia/pytorch:23.02-py3 #requires GPUs with compute capability of 5+
FROM nvcr.io/nvidia/pytorch:22.12-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt


# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
# do we need to disable IB?
# suggested to set ENV NCCL_IB_PCI_RELAXED_ORDERING to 0 for NCCL 2.18.1
ENV NCCL_IB_PCI_RELAXED_ORDERING="0" 
#ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV NCCL_P2P_PXN_LEVEL="0"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
ENV NCCL_IB_DISABLE="1"  
# ENV NCCL_P2P_DISABLE="1"
```
Here's my `pipeline.yaml`:
```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline



# <inputs_and_outputs>
inputs:

  training_data:
    type: uri_folder
    mode: download # pick ro_mount, rw_mount or download

outputs:
  checkpoints:
    type: uri_folder
    mode: upload
    path: azureml:my_model:1
  
    

# <jobs>
settings:
  default_datastore: azureml:mydatastore
  continue_on_step_failure: true

jobs:
  train:
    type: command
    component: file:train.yaml
    compute: azureml:mona-gpu-cluster # 16 GPUs
    resources:
      instance_count: 4    # number of nodes
    distribution:
      type: pytorch
      process_count_per_instance: 4 # number of gpus

    # NOTE: set env var if needed
    environment_variables:
      NCCL_DEBUG: "INFO" # adjusts the level of info from NCCL tests

      # NCCL_TOPO_FILE: "/opt/microsoft/ndv4-topo.xml" # Use specific topology file for A100

      # NCCL_IB_PCI_RELAXED_ORDERING: "1" # Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
      NCCL_IB_DISABLE: "1" # force disable infiniband (if set to "1")  # even if commented NCCL INFO NCCL_IB_DISABLE set by environment to 1.
      # NCCL_NET_PLUGIN: "none" # to force NET/Plugin off (no rdma/sharp plugin at all)
      # NCCL_NET: "Socket" # to force node-to-node comm to use Socket (slow)
      NCCL_SOCKET_IFNAME: "eth0" # to force Socket comm to use eth0 (use NCCL_NET=Socket)
      NCCL_P2P_PXN_LEVEL: "0"
      

      # UCX_IB_PCI_RELAXED_ORDERING: "on"
      # UCX_TLS: "tcp"
      # UCX_NET_DEVICES: "eth0" # if you have Error: Failed to resolve UCX endpoint...

      CUDA_DEVICE_ORDER: "PCI_BUS_ID" # ordering of gpus

      TORCH_DISTRIBUTED_DEBUG: "DETAIL"
      # NCCL_P2P_DISABLE: "1"

    inputs:
      train_data: ${{parent.inputs.training_data}}

      # data loading
      # batch_size: 256
      batch_size: 16
      manualseed: 42
      num_workers: 5
      prefetch_factor: 4
      persistent_workers: true
      pin_memory: true
      non_blocking: false

      # model
      model_arch: "vgg16"
      model_arch_pretrained: true

      # training
      num_epochs: 5 #need 60 for full training
      learning_rate: 0.0001
      momentum: 0.9

      # profiling
      enable_profiling: false
      # multiprocessing_sharing_strategy: "file_system" # WARNING: this can cause hang at job completion

      # Model Registrataion
      register_model_as: "mymodel"

# </jobs>

```
here's the `requirements.txt`:
```
albumentations==1.3.0
ConfigParser==5.3.0
horovod==0.27.0
matplotlib==3.7.0
numpy==1.24.2
nvisii==1.1.72
Pillow==9.4.0
profiling==0.1.3
psutil==5.9.0
pyquaternion==0.9.9
pyrealsense2==2.53.1.4623
pyrender==0.1.45
pyrr==0.10.3
PyYAML==6.0
scipy==1.10.1
seaborn==0.12.2
simplejson==3.18.4
tensorboardX==2.6
tqdm==4.64.1
opencv-python-headless==4.1.2.30
torch==1.13.0
torchvision==0.14.0
mlflow==2.3.2
azureml-mlflow==1.50.0
```

here's `train-env.yaml`:
```
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nvidia_pytorch
build:
  path: ../../../data-science/environment/
tags:
  os: ubuntu
  os_version: 20.04
  hpcx: 2.10
  mpi: openmpi
  mpi_version: 4.1.2rc4
  ucx: 1.12.0
  cuda: 11.6.2
  cudnn: 8.4.0.27
  # nccl: 2.12.10
  # nccl: 2.17.1
  nccl: 2.18.1
  rdma_core: 36.0
  nsight_compute: 2022.1.1.2
  nsight_systems: "2022.2.1.31-5fe97ab"
  nccl_test: 2.11.0
```

**Comment by sjeaugey** [comment]
I think that's again a PyTorch question. You should probably ask those on the PyTorch project.
