### ISSUE TITLE
RuntimeError when Running tokenizer on dataset

### ISSUE THREAD

**Issue by JOHNNY-fans** [NVIDIA/nccl#865]
Running tokenizer on dataset:  47%|███████████████▊                  | 3169000/6811963 [30:11<38:27, 1578.58 examples/s]Traceback (most recent call last):
  File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/train_sft.py", line 94, in <module>
    main()
  File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/train_sft.py", line 25, in main
    dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/utils/common.py", line 506, in preprocess_data
    with training_args.main_process_first(desc="dataset map pre-processing"):
  File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/site-packages/transformers/training_args.py", line 1891, in main_process_first
    torch.distributed.barrier()
  File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3328, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout

**Comment by yguo33** [comment]
Did you solve this problem? I got the same error message.
