### ISSUE TITLE
Cuda failure 'API call is not supported in the installed CUDA driver'

### ISSUE THREAD

**Issue by painshine** [NVIDIA/nccl#955]
I encountered an error during the training process ：
`NCCL_DEBUG=INFO TRANSFORMERS_VERBOSITY=info torchrun --nproc_per_node=2 train_test.py config.yaml --deepspeed=deepspeed_z3_config_bf16.json`

The complete error message is as follows：

```
2023-08-10 14:56:34 - INFO - datasets.arrow_dataset - Concatenating 12 shards
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO Bootstrap : Using eth0:10.221.109.254<0>
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO cudaDriverVersion 11000
NCCL version 2.14.3+cuda11.7
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO cudaDriverVersion 11000
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO NET/IB : No device found.
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO NET/Socket : Using [0]eth0:10.221.109.254<0>
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Using network Socket
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO Bootstrap : Using eth0:10.221.109.254<0>
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO NET/IB : No device found.
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO NET/Socket : Using [0]eth0:10.221.109.254<0>
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO Using network Socket
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO Setting affinity for GPU 1 to 1e00001e
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Setting affinity for GPU 0 to 1e00001e
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Channel 00/02 :    0   1
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Channel 01/02 :    0   1
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO Channel 00/0 : 1[5e000] -> 0[5a000] via P2P/IPC
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Channel 00/0 : 0[5a000] -> 1[5e000] via P2P/IPC
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO Channel 01/0 : 1[5e000] -> 0[5a000] via P2P/IPC
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO Channel 01/0 : 0[5a000] -> 1[5e000] via P2P/IPC

dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] transport/p2p.cc:209 NCCL WARN Cuda failure 'API call is not supported in the installed CUDA driver'
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO transport/p2p.cc:312 -> 1
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO transport.cc:124 -> 1

dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] transport/p2p.cc:209 NCCL WARN Cuda failure 'API call is not supported in the installed CUDA driver'
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO init.cc:790 -> 1
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO transport/p2p.cc:312 -> 1
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO transport.cc:124 -> 1
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO init.cc:1089 -> 1
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO init.cc:790 -> 1
dl-1509126880-pod-jupyter-m2gss:205827:205908 [1] NCCL INFO group.cc:64 -> 1 [Async thread]
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO init.cc:1089 -> 1
dl-1509126880-pod-jupyter-m2gss:205826:205907 [0] NCCL INFO group.cc:64 -> 1 [Async thread]
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO group.cc:421 -> 3
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO group.cc:421 -> 3
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO group.cc:106 -> 3
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO group.cc:106 -> 3
dl-1509126880-pod-jupyter-m2gss:205827:205909 [1] NCCL INFO [Service thread] Connection closed by localRank 1
dl-1509126880-pod-jupyter-m2gss:205826:205910 [0] NCCL INFO [Service thread] Connection closed by localRank 0
dl-1509126880-pod-jupyter-m2gss:205827:205827 [1] NCCL INFO comm 0x55b094b33930 rank 1 nranks 2 cudaDev 1 busId 5e000 - Abort COMPLETE
dl-1509126880-pod-jupyter-m2gss:205826:205826 [0] NCCL INFO comm 0x5577c9d9eba0 rank 0 nranks 2 cudaDev 0 busId 5a000 - Abort COMPLETE
Traceback (most recent call last):
  File "train_test.py", line 353, in <module>
Traceback (most recent call last):
  File "train_test.py", line 353, in <module>
    main()
  File "train_test.py", line 166, in main
    main()
  File "train_test.py", line 167, in main
    with training_args.main_process_first(desc="dataset map tokenization"):
  File "/root/.local/conda/envs/starcoder/lib/python3.8/contextlib.py", line 113, in __enter__
    tokenized_datasets = raw_datasets.map(
  File "/root/.local/conda/envs/starcoder/lib/python3.8/contextlib.py", line 120, in __exit__
    return next(self.gen)
  File "/root/.local/lib/python3.8/site-packages/transformers/training_args.py", line 1978, in main_process_first
    next(self.gen)
  File "/root/.local/lib/python3.8/site-packages/transformers/training_args.py", line 1987, in main_process_first
    dist.barrier()
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3328, in barrier
    dist.barrier()
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3328, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Cuda failure 'API call is not supported in the installed CUDA driver'
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Cuda failure 'API call is not supported in the installed CUDA driver'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 205826) of binary: /root/.local/conda/envs/starcoder/bin/python3.8
Traceback (most recent call last):
  File "/root/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-10_14:56:42
  host      : dl-1509126880-pod-jupyter-m2gss
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 205827)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-10_14:56:42
  host      : dl-1509126880-pod-jupyter-m2gss
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 205826)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

How can I solve this problem? Thank you for any helpful suggestions！

my environment:
```
GPUs: 8*V100

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

NCCL: nccl-repo-ubuntu1804-2.8.3-ga-cuda10.1

Python:  3.8.17
Pytorch: 1.7.1
```

**Comment by sjeaugey** [comment]
The error seems to be:
```
Cuda failure 'API call is not supported in the installed CUDA driver'
```
What is the driver version you are running? You can see it at the top of `nvidia-smi`.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
