### ISSUE TITLE
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.

### ISSUE THREAD

**Issue by caojlgyro** [NVIDIA/nccl#975]
I am using two 8-card H800 machines to test a PyTorch implementation similar to the nccl test script. The second host is reporting an error. How can I resolve it?

`n122-246-085:12246:12246 [0] NCCL INFO cudaDriverVersion 12020
n122-246-085:12246:12246 [0] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12252:12252 [6] NCCL INFO cudaDriverVersion 12020
n122-246-085:12252:12252 [6] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12253:12253 [7] NCCL INFO cudaDriverVersion 12020
n122-246-085:12253:12253 [7] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12251:12251 [5] NCCL INFO cudaDriverVersion 12020
n122-246-085:12251:12251 [5] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12247:12247 [1] NCCL INFO cudaDriverVersion 12020
n122-246-085:12247:12247 [1] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12249:12249 [3] NCCL INFO cudaDriverVersion 12020
n122-246-085:12249:12249 [3] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12250:12250 [4] NCCL INFO cudaDriverVersion 12020
n122-246-085:12250:12250 [4] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12248:12248 [2] NCCL INFO cudaDriverVersion 12020
n122-246-085:12248:12248 [2] NCCL INFO Bootstrap : Using ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12246:12397 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12246:12397 [0] NCCL INFO P2P plugin IBext
n122-246-085:12246:12397 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12246:12397 [0] NCCL INFO Using network IBext
n122-246-085:12252:12398 [6] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12252:12398 [6] NCCL INFO P2P plugin IBext
n122-246-085:12253:12399 [7] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12253:12399 [7] NCCL INFO P2P plugin IBext
n122-246-085:12251:12400 [5] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12251:12400 [5] NCCL INFO P2P plugin IBext
n122-246-085:12252:12398 [6] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12252:12398 [6] NCCL INFO Using network IBext
n122-246-085:12253:12399 [7] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12253:12399 [7] NCCL INFO Using network IBext
n122-246-085:12251:12400 [5] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12251:12400 [5] NCCL INFO Using network IBext
n122-246-085:12247:12401 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12247:12401 [1] NCCL INFO P2P plugin IBext
n122-246-085:12250:12403 [4] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12250:12403 [4] NCCL INFO P2P plugin IBext
n122-246-085:12249:12402 [3] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12249:12402 [3] NCCL INFO P2P plugin IBext
n122-246-085:12248:12404 [2] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
n122-246-085:12248:12404 [2] NCCL INFO P2P plugin IBext
n122-246-085:12247:12401 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12247:12401 [1] NCCL INFO Using network IBext
n122-246-085:12250:12403 [4] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12250:12403 [4] NCCL INFO Using network IBext
n122-246-085:12249:12402 [3] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12249:12402 [3] NCCL INFO Using network IBext
n122-246-085:12248:12404 [2] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB/SHARP [1]mlx5_2:1/IB/SHARP [2]mlx5_3:1/IB/SHARP [3]mlx5_4:1/IB/SHARP [4]mlx5_5:1/IB/SHARP [5]mlx5_6:1/IB/SHARP [6]mlx5_7:1/IB/SHARP [7]mlx5_8:1/IB/SHARP [8]mlx5_0:1/RoCE [RO]; OOB ib1:fe80::966d:ae03:b2:62c4%ib1<0>
n122-246-085:12248:12404 [2] NCCL INFO Using network IBext
n122-246-085:12250:12403 [4] NCCL INFO misc/socket.cc:504 -> 2 (Operation now in progress)
n122-246-085:12253:12399 [7] NCCL INFO misc/socket.cc:504 -> 2 (Operation now in progress)
n122-246-085:12250:12403 [4] NCCL INFO misc/socket.cc:567 -> 2
n122-246-085:12253:12399 [7] NCCL INFO misc/socket.cc:567 -> 2
n122-246-085:12250:12403 [4] NCCL INFO misc/socket.cc:618 -> 2
n122-246-085:12253:12399 [7] NCCL INFO misc/socket.cc:618 -> 2
n122-246-085:12250:12403 [4] NCCL INFO bootstrap.cc:270 -> 2
n122-246-085:12253:12399 [7] NCCL INFO bootstrap.cc:270 -> 2
n122-246-085:12250:12403 [4] NCCL INFO init.cc:1350 -> 2
n122-246-085:12253:12399 [7] NCCL INFO init.cc:1350 -> 2
n122-246-085:12250:12403 [4] NCCL INFO group.cc:65 -> 2 [Async thread]
n122-246-085:12253:12399 [7] NCCL INFO group.cc:65 -> 2 [Async thread]
n122-246-085:12250:12250 [4] NCCL INFO group.cc:406 -> 2
n122-246-085:12250:12250 [4] NCCL INFO group.cc:96 -> 2
n122-246-085:12253:12253 [7] NCCL INFO group.cc:406 -> 2
n122-246-085:12253:12253 [7] NCCL INFO group.cc:96 -> 2
n122-246-085:12246:12397 [0] NCCL INFO misc/socket.cc:504 -> 2 (Operation now in progress)
n122-246-085:12246:12397 [0] NCCL INFO misc/socket.cc:567 -> 2
n122-246-085:12246:12397 [0] NCCL INFO misc/socket.cc:618 -> 2
n122-246-085:12246:12397 [0] NCCL INFO bootstrap.cc:270 -> 2
n122-246-085:12246:12397 [0] NCCL INFO init.cc:1350 -> 2
n122-246-085:12246:12397 [0] NCCL INFO group.cc:65 -> 2 [Async thread]

n122-246-085:12251:12400 [5] misc/socket.cc:483 NCCL WARN socketStartConnect: Connect to fe80::966d:ae03:a2:8cf0%ib1<17943> failed : Software caused connection abort
n122-246-085:12251:12400 [5] NCCL INFO misc/socket.cc:564 -> 2
n122-246-085:12251:12400 [5] NCCL INFO misc/socket.cc:618 -> 2
n122-246-085:12251:12400 [5] NCCL INFO bootstrap.cc:270 -> 2
n122-246-085:12251:12400 [5] NCCL INFO init.cc:1350 -> 2

n122-246-085:12252:12398 [6] misc/socket.cc:483 NCCL WARN socketStartConnect: Connect to fe80::966d:ae03:a2:8cf0%ib1<17943> failed : Software caused connection abort
n122-246-085:12251:12400 [5] NCCL INFO group.cc:65 -> 2 [Async thread]
n122-246-085:12246:12246 [0] NCCL INFO group.cc:406 -> 2
n122-246-085:12252:12398 [6] NCCL INFO misc/socket.cc:564 -> 2
n122-246-085:12246:12246 [0] NCCL INFO group.cc:96 -> 2
n122-246-085:12252:12398 [6] NCCL INFO misc/socket.cc:618 -> 2
n122-246-085:12252:12398 [6] NCCL INFO bootstrap.cc:270 -> 2
n122-246-085:12252:12398 [6] NCCL INFO init.cc:1350 -> 2
n122-246-085:12252:12398 [6] NCCL INFO group.cc:65 -> 2 [Async thread]
n122-246-085:12251:12251 [5] NCCL INFO group.cc:406 -> 2
n122-246-085:12251:12251 [5] NCCL INFO group.cc:96 -> 2
n122-246-085:12252:12252 [6] NCCL INFO group.cc:406 -> 2
n122-246-085:12252:12252 [6] NCCL INFO group.cc:96 -> 2
n122-246-085:12253:12253 [7] NCCL INFO comm 0x55e39933f3b0 rank 15 nranks 16 cudaDev 7 busId 75010 - Abort COMPLETE
n122-246-085:12250:12250 [4] NCCL INFO comm 0x5654470b5a60 rank 12 nranks 16 cudaDev 4 busId 6f010 - Abort COMPLETE
n122-246-085:12246:12246 [0] NCCL INFO comm 0x561e0fe1c0f0 rank 8 nranks 16 cudaDev 0 busId 65010 - Abort COMPLETE
n122-246-085:12251:12251 [5] NCCL INFO comm 0x5606d4649430 rank 13 nranks 16 cudaDev 5 busId 71010 - Abort COMPLETE
n122-246-085:12252:12252 [6] NCCL INFO comm 0x55e94d699c30 rank 14 nranks 16 cudaDev 6 busId 73010 - Abort COMPLETE
Traceback (most recent call last):
  File "/workspace/torch_base_nccl.py", line 222, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
Traceback (most recent call last):
  File "/workspace/torch_base_nccl.py", line 222, in <module>
    return f(*args, **kwargs)
  File "/workspace/torch_base_nccl.py", line 197, in main
    test = TorchTestNccl(rank=dist.get_rank(), size=dist.get_world_size())
  File "/workspace/torch_base_nccl.py", line 43, in __init__
    main()
self.setup_3d_group()  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper

  File "/workspace/torch_base_nccl.py", line 78, in setup_3d_group
    torch.distributed.barrier()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3646, in barrier
    return f(*args, **kwargs)
  File "/workspace/torch_base_nccl.py", line 197, in main
    test = TorchTestNccl(rank=dist.get_rank(), size=dist.get_world_size())
  File "/workspace/torch_base_nccl.py", line 43, in __init__
    self.setup_3d_group()
  File "/workspace/torch_base_nccl.py", line 78, in setup_3d_group
    torch.distributed.barrier()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3646, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1182, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.3
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
Last error:`

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
